package cn.krt.zbcg.commons.bo.system;

import java.sql.Date;


public class ShqdheadBO {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shqdhead.id
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shqdhead.supplyid
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    private String supplyid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shqdhead.fhrq
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    private Date fhrq;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shqdhead.ysfs
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    private String ysfs;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shqdhead.lxdh
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    private String lxdh;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shqdhead.shr
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    private String shr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shqdhead.shdw
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    private String shdw;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shqdhead.chepaihao
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    private String chepaihao;
    
    public CustomerBO getCustomerBO() {
		return customerBO;
	}

	public void setCustomerBO(CustomerBO customerBO) {
		this.customerBO = customerBO;
	}

	private CustomerBO customerBO;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column shqdhead.id
     *
     * @return the value of shqdhead.id
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column shqdhead.id
     *
     * @param id the value for shqdhead.id
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column shqdhead.supplyid
     *
     * @return the value of shqdhead.supplyid
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    public String getSupplyid() {
        return supplyid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column shqdhead.supplyid
     *
     * @param supplyid the value for shqdhead.supplyid
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    public void setSupplyid(String supplyid) {
        this.supplyid = supplyid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column shqdhead.fhrq
     *
     * @return the value of shqdhead.fhrq
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    public Date getFhrq() {
        return fhrq;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column shqdhead.fhrq
     *
     * @param fhrq the value for shqdhead.fhrq
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    public void setFhrq(Date fhrq) {
        this.fhrq = fhrq;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column shqdhead.ysfs
     *
     * @return the value of shqdhead.ysfs
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    public String getYsfs() {
        return ysfs;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column shqdhead.ysfs
     *
     * @param ysfs the value for shqdhead.ysfs
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    public void setYsfs(String ysfs) {
        this.ysfs = ysfs;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column shqdhead.lxdh
     *
     * @return the value of shqdhead.lxdh
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    public String getLxdh() {
        return lxdh;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column shqdhead.lxdh
     *
     * @param lxdh the value for shqdhead.lxdh
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    public void setLxdh(String lxdh) {
        this.lxdh = lxdh;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column shqdhead.shr
     *
     * @return the value of shqdhead.shr
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    public String getShr() {
        return shr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column shqdhead.shr
     *
     * @param shr the value for shqdhead.shr
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    public void setShr(String shr) {
        this.shr = shr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column shqdhead.shdw
     *
     * @return the value of shqdhead.shdw
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    public String getShdw() {
        return shdw;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column shqdhead.shdw
     *
     * @param shdw the value for shqdhead.shdw
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    public void setShdw(String shdw) {
        this.shdw = shdw;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column shqdhead.chepaihao
     *
     * @return the value of shqdhead.chepaihao
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    public String getChepaihao() {
        return chepaihao;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column shqdhead.chepaihao
     *
     * @param chepaihao the value for shqdhead.chepaihao
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    public void setChepaihao(String chepaihao) {
        this.chepaihao = chepaihao;
    }
}