package cn.krt.zbcg.system.dao;

import cn.krt.zbcg.commons.bo.system.ShqdExample;
import cn.krt.zbcg.commons.bo.system.UserBO;

import java.util.List;
import cn.krt.zbcg.commons.bo.system.ShqdBO;

public interface ShqdDAO {
    /**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table shqd
	 * @abatorgenerated  Sat Sep 14 14:37:58 CST 2013
	 */
	void insert(ShqdBO record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table shqd
	 * @abatorgenerated  Sat Sep 14 14:37:58 CST 2013
	 */
	int updateByPrimaryKey(ShqdBO record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table shqd
	 * @abatorgenerated  Sat Sep 14 14:37:58 CST 2013
	 */
	int updateByPrimaryKeySelective(ShqdBO record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table shqd
	 * @abatorgenerated  Sat Sep 14 14:37:58 CST 2013
	 */
	List selectByExample(ShqdExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table shqd
	 * @abatorgenerated  Sat Sep 14 14:37:58 CST 2013
	 */
	ShqdBO selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table shqd
	 * @abatorgenerated  Sat Sep 14 14:37:58 CST 2013
	 */
	int deleteByExample(ShqdExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table shqd
	 * @abatorgenerated  Sat Sep 14 14:37:58 CST 2013
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table shqd
	 * @abatorgenerated  Sat Sep 14 14:37:58 CST 2013
	 */
	int countByExample(ShqdExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table shqd
	 * @abatorgenerated  Sat Sep 14 14:37:58 CST 2013
	 */
	int updateByExampleSelective(ShqdBO record, ShqdExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table shqd
	 * @abatorgenerated  Sat Sep 14 14:37:58 CST 2013
	 */
	int updateByExample(ShqdBO record, ShqdExample example);
	public abstract Object queryData(Object paramObject);
	
    public abstract List selectAll(Object paramObject);
	Object selectAllOfCount(Object obj);
    public abstract List selectAlls(Object paramObject);
    public abstract Object selectAllOfCounts(Object paramObject);

}