package cn.krt.zbcg.system.dao;

import cn.krt.zbcg.commons.bo.system.FapiaoinfoBO;
import cn.krt.zbcg.commons.bo.system.FapiaoinfoExample;
import cn.krt.zbcg.commons.bo.system.ShqdExample;

import java.util.List;
import cn.krt.zbcg.commons.bo.system.FapiaoinfoBO;

public interface FapiaoinfoDAO {
    /**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table fapiaoinfo
	 * @abatorgenerated  Wed Aug 14 20:17:14 CST 2013
	 */
	void insert(FapiaoinfoBO record);
	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table fapiaoinfo
	 * @abatorgenerated  Wed Aug 14 20:17:14 CST 2013
	 */
	int updateByPrimaryKey(FapiaoinfoBO record);
	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table fapiaoinfo
	 * @abatorgenerated  Wed Aug 14 20:17:14 CST 2013
	 */
	int updateByPrimaryKeySelective(FapiaoinfoBO record);
	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table fapiaoinfo
	 * @abatorgenerated  Wed Aug 14 20:17:14 CST 2013
	 */
	List selectByExample(FapiaoinfoExample example);
	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table fapiaoinfo
	 * @abatorgenerated  Wed Aug 14 20:17:14 CST 2013
	 */
	FapiaoinfoBO selectByPrimaryKey(Integer id);
	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table fapiaoinfo
	 * @abatorgenerated  Wed Aug 14 20:17:14 CST 2013
	 */
	int deleteByExample(FapiaoinfoExample example);
	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table fapiaoinfo
	 * @abatorgenerated  Wed Aug 14 20:17:14 CST 2013
	 */
	int deleteByPrimaryKey(Integer id);
	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table fapiaoinfo
	 * @abatorgenerated  Wed Aug 14 20:17:14 CST 2013
	 */
	int countByExample(FapiaoinfoExample example);
	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table fapiaoinfo
	 * @abatorgenerated  Wed Aug 14 20:17:14 CST 2013
	 */
	int updateByExampleSelective(FapiaoinfoBO record, FapiaoinfoExample example);
	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table fapiaoinfo
	 * @abatorgenerated  Wed Aug 14 20:17:14 CST 2013
	 */
	int updateByExample(FapiaoinfoBO record, FapiaoinfoExample example);
	int countByExample(ShqdExample example);
    public abstract List selectAll(Object paramObject);
	Object selectAllOfCount(Object obj);
    public abstract List selectAlls(Object paramObject);
    public abstract Object selectAllOfCounts(Object paramObject);
    FapiaoinfoBO queryData(FapiaoinfoBO key);

	int update(FapiaoinfoBO record) throws Exception;
}