package cn.krt.zbcg.system.web.form;


import org.ssi.struts.actionform.BaseForm;

import cn.krt.zbcg.commons.bo.system.ShqdBO;

public class ShqdForm  extends BaseForm{
	/**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shqd.id
     *
     * @abatorgenerated Wed Aug 07 22:37:50 CST 2013
     */
  
	private ShqdBO ShqdBO = new ShqdBO();
	

    public ShqdBO getShqdBO() {
		return ShqdBO;
	}

	public void setShqdBO(ShqdBO ShqdBO) {
		this.ShqdBO = ShqdBO;
	}


}
