package cn.krt.zbcg.commons.bo.system;

import java.sql.Date;


public class FapiaoinfoBO {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column fapiaoinfo.id
     *
     * @abatorgenerated Wed Aug 14 20:17:14 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column fapiaoinfo.jieshouriqi
     *
     * @abatorgenerated Wed Aug 14 20:17:14 CST 2013
     */
    private Date jieshouriqi;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column fapiaoinfo.gongyingshang
     *
     * @abatorgenerated Wed Aug 14 20:17:14 CST 2013
     */
    private String gongyingshang;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column fapiaoinfo.fapiaohao
     *
     * @abatorgenerated Wed Aug 14 20:17:14 CST 2013
     */
    private String fapiaohao;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column fapiaoinfo.kaipiaojiage
     *
     * @abatorgenerated Wed Aug 14 20:17:14 CST 2013
     */
    private Float kaipiaojiage;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column fapiaoinfo.kaipiaoriqi
     *
     * @abatorgenerated Wed Aug 14 20:17:14 CST 2013
     */
    private Date kaipiaoriqi;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column fapiaoinfo.piaomianxinxi
     *
     * @abatorgenerated Wed Aug 14 20:17:14 CST 2013
     */
    private String piaomianxinxi;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column fapiaoinfo.beizhu
     *
     * @abatorgenerated Wed Aug 14 20:17:14 CST 2013
     */
    private String beizhu;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column fapiaoinfo.id
     *
     * @return the value of fapiaoinfo.id
     *
     * @abatorgenerated Wed Aug 14 20:17:14 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column fapiaoinfo.id
     *
     * @param id the value for fapiaoinfo.id
     *
     * @abatorgenerated Wed Aug 14 20:17:14 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column fapiaoinfo.jieshouriqi
     *
     * @return the value of fapiaoinfo.jieshouriqi
     *
     * @abatorgenerated Wed Aug 14 20:17:14 CST 2013
     */
    public Date getJieshouriqi() {
        return jieshouriqi;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column fapiaoinfo.jieshouriqi
     *
     * @param jieshouriqi the value for fapiaoinfo.jieshouriqi
     *
     * @abatorgenerated Wed Aug 14 20:17:14 CST 2013
     */
    public void setJieshouriqi(Date jieshouriqi) {
        this.jieshouriqi = jieshouriqi;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column fapiaoinfo.gongyingshang
     *
     * @return the value of fapiaoinfo.gongyingshang
     *
     * @abatorgenerated Wed Aug 14 20:17:14 CST 2013
     */
    public String getGongyingshang() {
        return gongyingshang;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column fapiaoinfo.gongyingshang
     *
     * @param gongyingshang the value for fapiaoinfo.gongyingshang
     *
     * @abatorgenerated Wed Aug 14 20:17:14 CST 2013
     */
    public void setGongyingshang(String gongyingshang) {
        this.gongyingshang = gongyingshang;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column fapiaoinfo.fapiaohao
     *
     * @return the value of fapiaoinfo.fapiaohao
     *
     * @abatorgenerated Wed Aug 14 20:17:14 CST 2013
     */
    public String getFapiaohao() {
        return fapiaohao;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column fapiaoinfo.fapiaohao
     *
     * @param fapiaohao the value for fapiaoinfo.fapiaohao
     *
     * @abatorgenerated Wed Aug 14 20:17:14 CST 2013
     */
    public void setFapiaohao(String fapiaohao) {
        this.fapiaohao = fapiaohao;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column fapiaoinfo.kaipiaojiage
     *
     * @return the value of fapiaoinfo.kaipiaojiage
     *
     * @abatorgenerated Wed Aug 14 20:17:14 CST 2013
     */
    public Float getKaipiaojiage() {
        return kaipiaojiage;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column fapiaoinfo.kaipiaojiage
     *
     * @param kaipiaojiage the value for fapiaoinfo.kaipiaojiage
     *
     * @abatorgenerated Wed Aug 14 20:17:14 CST 2013
     */
    public void setKaipiaojiage(Float kaipiaojiage) {
        this.kaipiaojiage = kaipiaojiage;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column fapiaoinfo.kaipiaoriqi
     *
     * @return the value of fapiaoinfo.kaipiaoriqi
     *
     * @abatorgenerated Wed Aug 14 20:17:14 CST 2013
     */
    public Date getKaipiaoriqi() {
        return kaipiaoriqi;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column fapiaoinfo.kaipiaoriqi
     *
     * @param kaipiaoriqi the value for fapiaoinfo.kaipiaoriqi
     *
     * @abatorgenerated Wed Aug 14 20:17:14 CST 2013
     */
    public void setKaipiaoriqi(Date kaipiaoriqi) {
        this.kaipiaoriqi = kaipiaoriqi;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column fapiaoinfo.piaomianxinxi
     *
     * @return the value of fapiaoinfo.piaomianxinxi
     *
     * @abatorgenerated Wed Aug 14 20:17:14 CST 2013
     */
    public String getPiaomianxinxi() {
        return piaomianxinxi;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column fapiaoinfo.piaomianxinxi
     *
     * @param piaomianxinxi the value for fapiaoinfo.piaomianxinxi
     *
     * @abatorgenerated Wed Aug 14 20:17:14 CST 2013
     */
    public void setPiaomianxinxi(String piaomianxinxi) {
        this.piaomianxinxi = piaomianxinxi;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column fapiaoinfo.beizhu
     *
     * @return the value of fapiaoinfo.beizhu
     *
     * @abatorgenerated Wed Aug 14 20:17:14 CST 2013
     */
    public String getBeizhu() {
        return beizhu;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column fapiaoinfo.beizhu
     *
     * @param beizhu the value for fapiaoinfo.beizhu
     *
     * @abatorgenerated Wed Aug 14 20:17:14 CST 2013
     */
    public void setBeizhu(String beizhu) {
        this.beizhu = beizhu;
    }
}