package cn.krt.zbcg.commons.bo.system;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

public class FapiaoinfoExample {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table fapiaoinfo
	 * @abatorgenerated  Wed Aug 14 20:17:14 CST 2013
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table fapiaoinfo
	 * @abatorgenerated  Wed Aug 14 20:17:14 CST 2013
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table fapiaoinfo
	 * @abatorgenerated  Wed Aug 14 20:17:14 CST 2013
	 */
	public FapiaoinfoExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table fapiaoinfo
	 * @abatorgenerated  Wed Aug 14 20:17:14 CST 2013
	 */
	protected FapiaoinfoExample(FapiaoinfoExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table fapiaoinfo
	 * @abatorgenerated  Wed Aug 14 20:17:14 CST 2013
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table fapiaoinfo
	 * @abatorgenerated  Wed Aug 14 20:17:14 CST 2013
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table fapiaoinfo
	 * @abatorgenerated  Wed Aug 14 20:17:14 CST 2013
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table fapiaoinfo
	 * @abatorgenerated  Wed Aug 14 20:17:14 CST 2013
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table fapiaoinfo
	 * @abatorgenerated  Wed Aug 14 20:17:14 CST 2013
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table fapiaoinfo
	 * @abatorgenerated  Wed Aug 14 20:17:14 CST 2013
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table fapiaoinfo
	 * @abatorgenerated  Wed Aug 14 20:17:14 CST 2013
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table fapiaoinfo
	 * @abatorgenerated  Wed Aug 14 20:17:14 CST 2013
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		protected void addCriterionForJDBCDate(String condition, Date value,
				String property) {
			addCriterion(condition, new java.sql.Date(value.getTime()),
					property);
		}

		protected void addCriterionForJDBCDate(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			List dateList = new ArrayList();
			Iterator iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(((Date) iter.next()).getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1,
				Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()),
					new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return this;
		}

		public Criteria andIdIn(List values) {
			addCriterion("id in", values, "id");
			return this;
		}

		public Criteria andIdNotIn(List values) {
			addCriterion("id not in", values, "id");
			return this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return this;
		}

		public Criteria andJieshouriqiIsNull() {
			addCriterion("jieshouriqi is null");
			return this;
		}

		public Criteria andJieshouriqiIsNotNull() {
			addCriterion("jieshouriqi is not null");
			return this;
		}

		public Criteria andJieshouriqiEqualTo(Date value) {
			addCriterionForJDBCDate("jieshouriqi =", value, "jieshouriqi");
			return this;
		}

		public Criteria andJieshouriqiNotEqualTo(Date value) {
			addCriterionForJDBCDate("jieshouriqi <>", value, "jieshouriqi");
			return this;
		}

		public Criteria andJieshouriqiGreaterThan(Date value) {
			addCriterionForJDBCDate("jieshouriqi >", value, "jieshouriqi");
			return this;
		}

		public Criteria andJieshouriqiGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("jieshouriqi >=", value, "jieshouriqi");
			return this;
		}

		public Criteria andJieshouriqiLessThan(Date value) {
			addCriterionForJDBCDate("jieshouriqi <", value, "jieshouriqi");
			return this;
		}

		public Criteria andJieshouriqiLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("jieshouriqi <=", value, "jieshouriqi");
			return this;
		}

		public Criteria andJieshouriqiIn(List values) {
			addCriterionForJDBCDate("jieshouriqi in", values, "jieshouriqi");
			return this;
		}

		public Criteria andJieshouriqiNotIn(List values) {
			addCriterionForJDBCDate("jieshouriqi not in", values, "jieshouriqi");
			return this;
		}

		public Criteria andJieshouriqiBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("jieshouriqi between", value1, value2,
					"jieshouriqi");
			return this;
		}

		public Criteria andJieshouriqiNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("jieshouriqi not between", value1, value2,
					"jieshouriqi");
			return this;
		}

		public Criteria andGongyingshangIsNull() {
			addCriterion("gongyingshang is null");
			return this;
		}

		public Criteria andGongyingshangIsNotNull() {
			addCriterion("gongyingshang is not null");
			return this;
		}

		public Criteria andGongyingshangEqualTo(String value) {
			addCriterion("gongyingshang =", value, "gongyingshang");
			return this;
		}

		public Criteria andGongyingshangNotEqualTo(String value) {
			addCriterion("gongyingshang <>", value, "gongyingshang");
			return this;
		}

		public Criteria andGongyingshangGreaterThan(String value) {
			addCriterion("gongyingshang >", value, "gongyingshang");
			return this;
		}

		public Criteria andGongyingshangGreaterThanOrEqualTo(String value) {
			addCriterion("gongyingshang >=", value, "gongyingshang");
			return this;
		}

		public Criteria andGongyingshangLessThan(String value) {
			addCriterion("gongyingshang <", value, "gongyingshang");
			return this;
		}

		public Criteria andGongyingshangLessThanOrEqualTo(String value) {
			addCriterion("gongyingshang <=", value, "gongyingshang");
			return this;
		}

		public Criteria andGongyingshangLike(String value) {
			addCriterion("gongyingshang like", value, "gongyingshang");
			return this;
		}

		public Criteria andGongyingshangNotLike(String value) {
			addCriterion("gongyingshang not like", value, "gongyingshang");
			return this;
		}

		public Criteria andGongyingshangIn(List values) {
			addCriterion("gongyingshang in", values, "gongyingshang");
			return this;
		}

		public Criteria andGongyingshangNotIn(List values) {
			addCriterion("gongyingshang not in", values, "gongyingshang");
			return this;
		}

		public Criteria andGongyingshangBetween(String value1, String value2) {
			addCriterion("gongyingshang between", value1, value2,
					"gongyingshang");
			return this;
		}

		public Criteria andGongyingshangNotBetween(String value1, String value2) {
			addCriterion("gongyingshang not between", value1, value2,
					"gongyingshang");
			return this;
		}

		public Criteria andFapiaohaoIsNull() {
			addCriterion("fapiaohao is null");
			return this;
		}

		public Criteria andFapiaohaoIsNotNull() {
			addCriterion("fapiaohao is not null");
			return this;
		}

		public Criteria andFapiaohaoEqualTo(String value) {
			addCriterion("fapiaohao =", value, "fapiaohao");
			return this;
		}

		public Criteria andFapiaohaoNotEqualTo(String value) {
			addCriterion("fapiaohao <>", value, "fapiaohao");
			return this;
		}

		public Criteria andFapiaohaoGreaterThan(String value) {
			addCriterion("fapiaohao >", value, "fapiaohao");
			return this;
		}

		public Criteria andFapiaohaoGreaterThanOrEqualTo(String value) {
			addCriterion("fapiaohao >=", value, "fapiaohao");
			return this;
		}

		public Criteria andFapiaohaoLessThan(String value) {
			addCriterion("fapiaohao <", value, "fapiaohao");
			return this;
		}

		public Criteria andFapiaohaoLessThanOrEqualTo(String value) {
			addCriterion("fapiaohao <=", value, "fapiaohao");
			return this;
		}

		public Criteria andFapiaohaoLike(String value) {
			addCriterion("fapiaohao like", value, "fapiaohao");
			return this;
		}

		public Criteria andFapiaohaoNotLike(String value) {
			addCriterion("fapiaohao not like", value, "fapiaohao");
			return this;
		}

		public Criteria andFapiaohaoIn(List values) {
			addCriterion("fapiaohao in", values, "fapiaohao");
			return this;
		}

		public Criteria andFapiaohaoNotIn(List values) {
			addCriterion("fapiaohao not in", values, "fapiaohao");
			return this;
		}

		public Criteria andFapiaohaoBetween(String value1, String value2) {
			addCriterion("fapiaohao between", value1, value2, "fapiaohao");
			return this;
		}

		public Criteria andFapiaohaoNotBetween(String value1, String value2) {
			addCriterion("fapiaohao not between", value1, value2, "fapiaohao");
			return this;
		}

		public Criteria andKaipiaojiageIsNull() {
			addCriterion("kaipiaojiage is null");
			return this;
		}

		public Criteria andKaipiaojiageIsNotNull() {
			addCriterion("kaipiaojiage is not null");
			return this;
		}

		public Criteria andKaipiaojiageEqualTo(Float value) {
			addCriterion("kaipiaojiage =", value, "kaipiaojiage");
			return this;
		}

		public Criteria andKaipiaojiageNotEqualTo(Float value) {
			addCriterion("kaipiaojiage <>", value, "kaipiaojiage");
			return this;
		}

		public Criteria andKaipiaojiageGreaterThan(Float value) {
			addCriterion("kaipiaojiage >", value, "kaipiaojiage");
			return this;
		}

		public Criteria andKaipiaojiageGreaterThanOrEqualTo(Float value) {
			addCriterion("kaipiaojiage >=", value, "kaipiaojiage");
			return this;
		}

		public Criteria andKaipiaojiageLessThan(Float value) {
			addCriterion("kaipiaojiage <", value, "kaipiaojiage");
			return this;
		}

		public Criteria andKaipiaojiageLessThanOrEqualTo(Float value) {
			addCriterion("kaipiaojiage <=", value, "kaipiaojiage");
			return this;
		}

		public Criteria andKaipiaojiageIn(List values) {
			addCriterion("kaipiaojiage in", values, "kaipiaojiage");
			return this;
		}

		public Criteria andKaipiaojiageNotIn(List values) {
			addCriterion("kaipiaojiage not in", values, "kaipiaojiage");
			return this;
		}

		public Criteria andKaipiaojiageBetween(Float value1, Float value2) {
			addCriterion("kaipiaojiage between", value1, value2, "kaipiaojiage");
			return this;
		}

		public Criteria andKaipiaojiageNotBetween(Float value1, Float value2) {
			addCriterion("kaipiaojiage not between", value1, value2,
					"kaipiaojiage");
			return this;
		}

		public Criteria andKaipiaoriqiIsNull() {
			addCriterion("kaipiaoriqi is null");
			return this;
		}

		public Criteria andKaipiaoriqiIsNotNull() {
			addCriterion("kaipiaoriqi is not null");
			return this;
		}

		public Criteria andKaipiaoriqiEqualTo(Date value) {
			addCriterionForJDBCDate("kaipiaoriqi =", value, "kaipiaoriqi");
			return this;
		}

		public Criteria andKaipiaoriqiNotEqualTo(Date value) {
			addCriterionForJDBCDate("kaipiaoriqi <>", value, "kaipiaoriqi");
			return this;
		}

		public Criteria andKaipiaoriqiGreaterThan(Date value) {
			addCriterionForJDBCDate("kaipiaoriqi >", value, "kaipiaoriqi");
			return this;
		}

		public Criteria andKaipiaoriqiGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("kaipiaoriqi >=", value, "kaipiaoriqi");
			return this;
		}

		public Criteria andKaipiaoriqiLessThan(Date value) {
			addCriterionForJDBCDate("kaipiaoriqi <", value, "kaipiaoriqi");
			return this;
		}

		public Criteria andKaipiaoriqiLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("kaipiaoriqi <=", value, "kaipiaoriqi");
			return this;
		}

		public Criteria andKaipiaoriqiIn(List values) {
			addCriterionForJDBCDate("kaipiaoriqi in", values, "kaipiaoriqi");
			return this;
		}

		public Criteria andKaipiaoriqiNotIn(List values) {
			addCriterionForJDBCDate("kaipiaoriqi not in", values, "kaipiaoriqi");
			return this;
		}

		public Criteria andKaipiaoriqiBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("kaipiaoriqi between", value1, value2,
					"kaipiaoriqi");
			return this;
		}

		public Criteria andKaipiaoriqiNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("kaipiaoriqi not between", value1, value2,
					"kaipiaoriqi");
			return this;
		}

		public Criteria andPiaomianxinxiIsNull() {
			addCriterion("piaomianxinxi is null");
			return this;
		}

		public Criteria andPiaomianxinxiIsNotNull() {
			addCriterion("piaomianxinxi is not null");
			return this;
		}

		public Criteria andPiaomianxinxiEqualTo(String value) {
			addCriterion("piaomianxinxi =", value, "piaomianxinxi");
			return this;
		}

		public Criteria andPiaomianxinxiNotEqualTo(String value) {
			addCriterion("piaomianxinxi <>", value, "piaomianxinxi");
			return this;
		}

		public Criteria andPiaomianxinxiGreaterThan(String value) {
			addCriterion("piaomianxinxi >", value, "piaomianxinxi");
			return this;
		}

		public Criteria andPiaomianxinxiGreaterThanOrEqualTo(String value) {
			addCriterion("piaomianxinxi >=", value, "piaomianxinxi");
			return this;
		}

		public Criteria andPiaomianxinxiLessThan(String value) {
			addCriterion("piaomianxinxi <", value, "piaomianxinxi");
			return this;
		}

		public Criteria andPiaomianxinxiLessThanOrEqualTo(String value) {
			addCriterion("piaomianxinxi <=", value, "piaomianxinxi");
			return this;
		}

		public Criteria andPiaomianxinxiLike(String value) {
			addCriterion("piaomianxinxi like", value, "piaomianxinxi");
			return this;
		}

		public Criteria andPiaomianxinxiNotLike(String value) {
			addCriterion("piaomianxinxi not like", value, "piaomianxinxi");
			return this;
		}

		public Criteria andPiaomianxinxiIn(List values) {
			addCriterion("piaomianxinxi in", values, "piaomianxinxi");
			return this;
		}

		public Criteria andPiaomianxinxiNotIn(List values) {
			addCriterion("piaomianxinxi not in", values, "piaomianxinxi");
			return this;
		}

		public Criteria andPiaomianxinxiBetween(String value1, String value2) {
			addCriterion("piaomianxinxi between", value1, value2,
					"piaomianxinxi");
			return this;
		}

		public Criteria andPiaomianxinxiNotBetween(String value1, String value2) {
			addCriterion("piaomianxinxi not between", value1, value2,
					"piaomianxinxi");
			return this;
		}

		public Criteria andBeizhuIsNull() {
			addCriterion("beizhu is null");
			return this;
		}

		public Criteria andBeizhuIsNotNull() {
			addCriterion("beizhu is not null");
			return this;
		}

		public Criteria andBeizhuEqualTo(String value) {
			addCriterion("beizhu =", value, "beizhu");
			return this;
		}

		public Criteria andBeizhuNotEqualTo(String value) {
			addCriterion("beizhu <>", value, "beizhu");
			return this;
		}

		public Criteria andBeizhuGreaterThan(String value) {
			addCriterion("beizhu >", value, "beizhu");
			return this;
		}

		public Criteria andBeizhuGreaterThanOrEqualTo(String value) {
			addCriterion("beizhu >=", value, "beizhu");
			return this;
		}

		public Criteria andBeizhuLessThan(String value) {
			addCriterion("beizhu <", value, "beizhu");
			return this;
		}

		public Criteria andBeizhuLessThanOrEqualTo(String value) {
			addCriterion("beizhu <=", value, "beizhu");
			return this;
		}

		public Criteria andBeizhuLike(String value) {
			addCriterion("beizhu like", value, "beizhu");
			return this;
		}

		public Criteria andBeizhuNotLike(String value) {
			addCriterion("beizhu not like", value, "beizhu");
			return this;
		}

		public Criteria andBeizhuIn(List values) {
			addCriterion("beizhu in", values, "beizhu");
			return this;
		}

		public Criteria andBeizhuNotIn(List values) {
			addCriterion("beizhu not in", values, "beizhu");
			return this;
		}

		public Criteria andBeizhuBetween(String value1, String value2) {
			addCriterion("beizhu between", value1, value2, "beizhu");
			return this;
		}

		public Criteria andBeizhuNotBetween(String value1, String value2) {
			addCriterion("beizhu not between", value1, value2, "beizhu");
			return this;
		}
	}
}