package cn.krt.zbcg.commons.bo.system;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

public class ShqdheadExample {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table shqdhead
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table shqdhead
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    protected List oredCriteria;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shqdhead
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    public ShqdheadExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shqdhead
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    protected ShqdheadExample(ShqdheadExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shqdhead
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shqdhead
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shqdhead
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shqdhead
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shqdhead
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shqdhead
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shqdhead
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table shqdhead
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List dateList = new ArrayList();
            Iterator iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(((Date)iter.next()).getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return this;
        }

        public Criteria andIdIn(List values) {
            addCriterion("id in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List values) {
            addCriterion("id not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return this;
        }

        public Criteria andSupplyidIsNull() {
            addCriterion("supplyid is null");
            return this;
        }

        public Criteria andSupplyidIsNotNull() {
            addCriterion("supplyid is not null");
            return this;
        }

        public Criteria andSupplyidEqualTo(String value) {
            addCriterion("supplyid =", value, "supplyid");
            return this;
        }

        public Criteria andSupplyidNotEqualTo(String value) {
            addCriterion("supplyid <>", value, "supplyid");
            return this;
        }

        public Criteria andSupplyidGreaterThan(String value) {
            addCriterion("supplyid >", value, "supplyid");
            return this;
        }

        public Criteria andSupplyidGreaterThanOrEqualTo(String value) {
            addCriterion("supplyid >=", value, "supplyid");
            return this;
        }

        public Criteria andSupplyidLessThan(String value) {
            addCriterion("supplyid <", value, "supplyid");
            return this;
        }

        public Criteria andSupplyidLessThanOrEqualTo(String value) {
            addCriterion("supplyid <=", value, "supplyid");
            return this;
        }

        public Criteria andSupplyidLike(String value) {
            addCriterion("supplyid like", value, "supplyid");
            return this;
        }

        public Criteria andSupplyidNotLike(String value) {
            addCriterion("supplyid not like", value, "supplyid");
            return this;
        }

        public Criteria andSupplyidIn(List values) {
            addCriterion("supplyid in", values, "supplyid");
            return this;
        }

        public Criteria andSupplyidNotIn(List values) {
            addCriterion("supplyid not in", values, "supplyid");
            return this;
        }

        public Criteria andSupplyidBetween(String value1, String value2) {
            addCriterion("supplyid between", value1, value2, "supplyid");
            return this;
        }

        public Criteria andSupplyidNotBetween(String value1, String value2) {
            addCriterion("supplyid not between", value1, value2, "supplyid");
            return this;
        }

        public Criteria andFhrqIsNull() {
            addCriterion("fhrq is null");
            return this;
        }

        public Criteria andFhrqIsNotNull() {
            addCriterion("fhrq is not null");
            return this;
        }

        public Criteria andFhrqEqualTo(Date value) {
            addCriterionForJDBCDate("fhrq =", value, "fhrq");
            return this;
        }

        public Criteria andFhrqNotEqualTo(Date value) {
            addCriterionForJDBCDate("fhrq <>", value, "fhrq");
            return this;
        }

        public Criteria andFhrqGreaterThan(Date value) {
            addCriterionForJDBCDate("fhrq >", value, "fhrq");
            return this;
        }

        public Criteria andFhrqGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("fhrq >=", value, "fhrq");
            return this;
        }

        public Criteria andFhrqLessThan(Date value) {
            addCriterionForJDBCDate("fhrq <", value, "fhrq");
            return this;
        }

        public Criteria andFhrqLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("fhrq <=", value, "fhrq");
            return this;
        }

        public Criteria andFhrqIn(List values) {
            addCriterionForJDBCDate("fhrq in", values, "fhrq");
            return this;
        }

        public Criteria andFhrqNotIn(List values) {
            addCriterionForJDBCDate("fhrq not in", values, "fhrq");
            return this;
        }

        public Criteria andFhrqBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("fhrq between", value1, value2, "fhrq");
            return this;
        }

        public Criteria andFhrqNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("fhrq not between", value1, value2, "fhrq");
            return this;
        }

        public Criteria andYsfsIsNull() {
            addCriterion("ysfs is null");
            return this;
        }

        public Criteria andYsfsIsNotNull() {
            addCriterion("ysfs is not null");
            return this;
        }

        public Criteria andYsfsEqualTo(String value) {
            addCriterion("ysfs =", value, "ysfs");
            return this;
        }

        public Criteria andYsfsNotEqualTo(String value) {
            addCriterion("ysfs <>", value, "ysfs");
            return this;
        }

        public Criteria andYsfsGreaterThan(String value) {
            addCriterion("ysfs >", value, "ysfs");
            return this;
        }

        public Criteria andYsfsGreaterThanOrEqualTo(String value) {
            addCriterion("ysfs >=", value, "ysfs");
            return this;
        }

        public Criteria andYsfsLessThan(String value) {
            addCriterion("ysfs <", value, "ysfs");
            return this;
        }

        public Criteria andYsfsLessThanOrEqualTo(String value) {
            addCriterion("ysfs <=", value, "ysfs");
            return this;
        }

        public Criteria andYsfsLike(String value) {
            addCriterion("ysfs like", value, "ysfs");
            return this;
        }

        public Criteria andYsfsNotLike(String value) {
            addCriterion("ysfs not like", value, "ysfs");
            return this;
        }

        public Criteria andYsfsIn(List values) {
            addCriterion("ysfs in", values, "ysfs");
            return this;
        }

        public Criteria andYsfsNotIn(List values) {
            addCriterion("ysfs not in", values, "ysfs");
            return this;
        }

        public Criteria andYsfsBetween(String value1, String value2) {
            addCriterion("ysfs between", value1, value2, "ysfs");
            return this;
        }

        public Criteria andYsfsNotBetween(String value1, String value2) {
            addCriterion("ysfs not between", value1, value2, "ysfs");
            return this;
        }

        public Criteria andLxdhIsNull() {
            addCriterion("lxdh is null");
            return this;
        }

        public Criteria andLxdhIsNotNull() {
            addCriterion("lxdh is not null");
            return this;
        }

        public Criteria andLxdhEqualTo(String value) {
            addCriterion("lxdh =", value, "lxdh");
            return this;
        }

        public Criteria andLxdhNotEqualTo(String value) {
            addCriterion("lxdh <>", value, "lxdh");
            return this;
        }

        public Criteria andLxdhGreaterThan(String value) {
            addCriterion("lxdh >", value, "lxdh");
            return this;
        }

        public Criteria andLxdhGreaterThanOrEqualTo(String value) {
            addCriterion("lxdh >=", value, "lxdh");
            return this;
        }

        public Criteria andLxdhLessThan(String value) {
            addCriterion("lxdh <", value, "lxdh");
            return this;
        }

        public Criteria andLxdhLessThanOrEqualTo(String value) {
            addCriterion("lxdh <=", value, "lxdh");
            return this;
        }

        public Criteria andLxdhLike(String value) {
            addCriterion("lxdh like", value, "lxdh");
            return this;
        }

        public Criteria andLxdhNotLike(String value) {
            addCriterion("lxdh not like", value, "lxdh");
            return this;
        }

        public Criteria andLxdhIn(List values) {
            addCriterion("lxdh in", values, "lxdh");
            return this;
        }

        public Criteria andLxdhNotIn(List values) {
            addCriterion("lxdh not in", values, "lxdh");
            return this;
        }

        public Criteria andLxdhBetween(String value1, String value2) {
            addCriterion("lxdh between", value1, value2, "lxdh");
            return this;
        }

        public Criteria andLxdhNotBetween(String value1, String value2) {
            addCriterion("lxdh not between", value1, value2, "lxdh");
            return this;
        }

        public Criteria andShrIsNull() {
            addCriterion("shr is null");
            return this;
        }

        public Criteria andShrIsNotNull() {
            addCriterion("shr is not null");
            return this;
        }

        public Criteria andShrEqualTo(String value) {
            addCriterion("shr =", value, "shr");
            return this;
        }

        public Criteria andShrNotEqualTo(String value) {
            addCriterion("shr <>", value, "shr");
            return this;
        }

        public Criteria andShrGreaterThan(String value) {
            addCriterion("shr >", value, "shr");
            return this;
        }

        public Criteria andShrGreaterThanOrEqualTo(String value) {
            addCriterion("shr >=", value, "shr");
            return this;
        }

        public Criteria andShrLessThan(String value) {
            addCriterion("shr <", value, "shr");
            return this;
        }

        public Criteria andShrLessThanOrEqualTo(String value) {
            addCriterion("shr <=", value, "shr");
            return this;
        }

        public Criteria andShrLike(String value) {
            addCriterion("shr like", value, "shr");
            return this;
        }

        public Criteria andShrNotLike(String value) {
            addCriterion("shr not like", value, "shr");
            return this;
        }

        public Criteria andShrIn(List values) {
            addCriterion("shr in", values, "shr");
            return this;
        }

        public Criteria andShrNotIn(List values) {
            addCriterion("shr not in", values, "shr");
            return this;
        }

        public Criteria andShrBetween(String value1, String value2) {
            addCriterion("shr between", value1, value2, "shr");
            return this;
        }

        public Criteria andShrNotBetween(String value1, String value2) {
            addCriterion("shr not between", value1, value2, "shr");
            return this;
        }

        public Criteria andShdwIsNull() {
            addCriterion("shdw is null");
            return this;
        }

        public Criteria andShdwIsNotNull() {
            addCriterion("shdw is not null");
            return this;
        }

        public Criteria andShdwEqualTo(String value) {
            addCriterion("shdw =", value, "shdw");
            return this;
        }

        public Criteria andShdwNotEqualTo(String value) {
            addCriterion("shdw <>", value, "shdw");
            return this;
        }

        public Criteria andShdwGreaterThan(String value) {
            addCriterion("shdw >", value, "shdw");
            return this;
        }

        public Criteria andShdwGreaterThanOrEqualTo(String value) {
            addCriterion("shdw >=", value, "shdw");
            return this;
        }

        public Criteria andShdwLessThan(String value) {
            addCriterion("shdw <", value, "shdw");
            return this;
        }

        public Criteria andShdwLessThanOrEqualTo(String value) {
            addCriterion("shdw <=", value, "shdw");
            return this;
        }

        public Criteria andShdwLike(String value) {
            addCriterion("shdw like", value, "shdw");
            return this;
        }

        public Criteria andShdwNotLike(String value) {
            addCriterion("shdw not like", value, "shdw");
            return this;
        }

        public Criteria andShdwIn(List values) {
            addCriterion("shdw in", values, "shdw");
            return this;
        }

        public Criteria andShdwNotIn(List values) {
            addCriterion("shdw not in", values, "shdw");
            return this;
        }

        public Criteria andShdwBetween(String value1, String value2) {
            addCriterion("shdw between", value1, value2, "shdw");
            return this;
        }

        public Criteria andShdwNotBetween(String value1, String value2) {
            addCriterion("shdw not between", value1, value2, "shdw");
            return this;
        }

        public Criteria andChepaihaoIsNull() {
            addCriterion("chepaihao is null");
            return this;
        }

        public Criteria andChepaihaoIsNotNull() {
            addCriterion("chepaihao is not null");
            return this;
        }

        public Criteria andChepaihaoEqualTo(String value) {
            addCriterion("chepaihao =", value, "chepaihao");
            return this;
        }

        public Criteria andChepaihaoNotEqualTo(String value) {
            addCriterion("chepaihao <>", value, "chepaihao");
            return this;
        }

        public Criteria andChepaihaoGreaterThan(String value) {
            addCriterion("chepaihao >", value, "chepaihao");
            return this;
        }

        public Criteria andChepaihaoGreaterThanOrEqualTo(String value) {
            addCriterion("chepaihao >=", value, "chepaihao");
            return this;
        }

        public Criteria andChepaihaoLessThan(String value) {
            addCriterion("chepaihao <", value, "chepaihao");
            return this;
        }

        public Criteria andChepaihaoLessThanOrEqualTo(String value) {
            addCriterion("chepaihao <=", value, "chepaihao");
            return this;
        }

        public Criteria andChepaihaoLike(String value) {
            addCriterion("chepaihao like", value, "chepaihao");
            return this;
        }

        public Criteria andChepaihaoNotLike(String value) {
            addCriterion("chepaihao not like", value, "chepaihao");
            return this;
        }

        public Criteria andChepaihaoIn(List values) {
            addCriterion("chepaihao in", values, "chepaihao");
            return this;
        }

        public Criteria andChepaihaoNotIn(List values) {
            addCriterion("chepaihao not in", values, "chepaihao");
            return this;
        }

        public Criteria andChepaihaoBetween(String value1, String value2) {
            addCriterion("chepaihao between", value1, value2, "chepaihao");
            return this;
        }

        public Criteria andChepaihaoNotBetween(String value1, String value2) {
            addCriterion("chepaihao not between", value1, value2, "chepaihao");
            return this;
        }
    }
}