package cn.krt.zbcg.commons.bo.system;

public class ShqdBO {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shqd.id
     *
     * @abatorgenerated Sat Sep 14 14:37:58 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shqd.pinzhongid
     *
     * @abatorgenerated Sat Sep 14 14:37:58 CST 2013
     */
    private Integer pinzhongid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shqd.guige
     *
     * @abatorgenerated Sat Sep 14 14:37:58 CST 2013
     */
    private String guige;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shqd.jianshu
     *
     * @abatorgenerated Sat Sep 14 14:37:58 CST 2013
     */
    private String jianshu;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shqd.laihuoshuliang
     *
     * @abatorgenerated Sat Sep 14 14:37:58 CST 2013
     */
    private String laihuoshuliang;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shqd.shishoushuliang
     *
     * @abatorgenerated Sat Sep 14 14:37:58 CST 2013
     */
    private String shishoushuliang;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shqd.chandi
     *
     * @abatorgenerated Sat Sep 14 14:37:58 CST 2013
     */
    private String chandi;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shqd.beizhu
     *
     * @abatorgenerated Sat Sep 14 14:37:58 CST 2013
     */
    private String beizhu;
    
    private  MedicineBO medicineBO;
    
    
    public MedicineBO getMedicineBO() {
		return medicineBO;
	}

	public void setMedicineBO(MedicineBO medicineBO) {
		this.medicineBO = medicineBO;
	}

	private String shqdheadid;

    public String getShqdheadid() {
		return shqdheadid;
	}

	public void setShqdheadid(String shqdheadid) {
		this.shqdheadid = shqdheadid;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column shqd.id
     *
     * @return the value of shqd.id
     *
     * @abatorgenerated Sat Sep 14 14:37:58 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column shqd.id
     *
     * @param id the value for shqd.id
     *
     * @abatorgenerated Sat Sep 14 14:37:58 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column shqd.pinzhongid
     *
     * @return the value of shqd.pinzhongid
     *
     * @abatorgenerated Sat Sep 14 14:37:58 CST 2013
     */
    public Integer getPinzhongid() {
        return pinzhongid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column shqd.pinzhongid
     *
     * @param pinzhongid the value for shqd.pinzhongid
     *
     * @abatorgenerated Sat Sep 14 14:37:58 CST 2013
     */
    public void setPinzhongid(Integer pinzhongid) {
        this.pinzhongid = pinzhongid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column shqd.guige
     *
     * @return the value of shqd.guige
     *
     * @abatorgenerated Sat Sep 14 14:37:58 CST 2013
     */
    public String getGuige() {
        return guige;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column shqd.guige
     *
     * @param guige the value for shqd.guige
     *
     * @abatorgenerated Sat Sep 14 14:37:58 CST 2013
     */
    public void setGuige(String guige) {
        this.guige = guige;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column shqd.jianshu
     *
     * @return the value of shqd.jianshu
     *
     * @abatorgenerated Sat Sep 14 14:37:58 CST 2013
     */
    public String getJianshu() {
        return jianshu;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column shqd.jianshu
     *
     * @param jianshu the value for shqd.jianshu
     *
     * @abatorgenerated Sat Sep 14 14:37:58 CST 2013
     */
    public void setJianshu(String jianshu) {
        this.jianshu = jianshu;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column shqd.laihuoshuliang
     *
     * @return the value of shqd.laihuoshuliang
     *
     * @abatorgenerated Sat Sep 14 14:37:58 CST 2013
     */
    public String getLaihuoshuliang() {
        return laihuoshuliang;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column shqd.laihuoshuliang
     *
     * @param laihuoshuliang the value for shqd.laihuoshuliang
     *
     * @abatorgenerated Sat Sep 14 14:37:58 CST 2013
     */
    public void setLaihuoshuliang(String laihuoshuliang) {
        this.laihuoshuliang = laihuoshuliang;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column shqd.shishoushuliang
     *
     * @return the value of shqd.shishoushuliang
     *
     * @abatorgenerated Sat Sep 14 14:37:58 CST 2013
     */
    public String getShishoushuliang() {
        return shishoushuliang;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column shqd.shishoushuliang
     *
     * @param shishoushuliang the value for shqd.shishoushuliang
     *
     * @abatorgenerated Sat Sep 14 14:37:58 CST 2013
     */
    public void setShishoushuliang(String shishoushuliang) {
        this.shishoushuliang = shishoushuliang;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column shqd.chandi
     *
     * @return the value of shqd.chandi
     *
     * @abatorgenerated Sat Sep 14 14:37:58 CST 2013
     */
    public String getChandi() {
        return chandi;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column shqd.chandi
     *
     * @param chandi the value for shqd.chandi
     *
     * @abatorgenerated Sat Sep 14 14:37:58 CST 2013
     */
    public void setChandi(String chandi) {
        this.chandi = chandi;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column shqd.beizhu
     *
     * @return the value of shqd.beizhu
     *
     * @abatorgenerated Sat Sep 14 14:37:58 CST 2013
     */
    public String getBeizhu() {
        return beizhu;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column shqd.beizhu
     *
     * @param beizhu the value for shqd.beizhu
     *
     * @abatorgenerated Sat Sep 14 14:37:58 CST 2013
     */
    public void setBeizhu(String beizhu) {
        this.beizhu = beizhu;
    }
}