package cn.krt.zbcg.commons.bo.system;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class StorageExample {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table storage
     *
     * @abatorgenerated Sun Jul 21 12:52:32 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table storage
     *
     * @abatorgenerated Sun Jul 21 12:52:32 CST 2013
     */
    protected List oredCriteria;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table storage
     *
     * @abatorgenerated Sun Jul 21 12:52:32 CST 2013
     */
    public StorageExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table storage
     *
     * @abatorgenerated Sun Jul 21 12:52:32 CST 2013
     */
    protected StorageExample(StorageExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table storage
     *
     * @abatorgenerated Sun Jul 21 12:52:32 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table storage
     *
     * @abatorgenerated Sun Jul 21 12:52:32 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table storage
     *
     * @abatorgenerated Sun Jul 21 12:52:32 CST 2013
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table storage
     *
     * @abatorgenerated Sun Jul 21 12:52:32 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table storage
     *
     * @abatorgenerated Sun Jul 21 12:52:32 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table storage
     *
     * @abatorgenerated Sun Jul 21 12:52:32 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table storage
     *
     * @abatorgenerated Sun Jul 21 12:52:32 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table storage
     *
     * @abatorgenerated Sun Jul 21 12:52:32 CST 2013
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return this;
        }

        public Criteria andIdIn(List values) {
            addCriterion("id in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List values) {
            addCriterion("id not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return this;
        }

        public Criteria andNameIn(List values) {
            addCriterion("name in", values, "name");
            return this;
        }

        public Criteria andNameNotIn(List values) {
            addCriterion("name not in", values, "name");
            return this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return this;
        }

        public Criteria andPinhaoIsNull() {
            addCriterion("pinhao is null");
            return this;
        }

        public Criteria andPinhaoIsNotNull() {
            addCriterion("pinhao is not null");
            return this;
        }

        public Criteria andPinhaoEqualTo(String value) {
            addCriterion("pinhao =", value, "pinhao");
            return this;
        }

        public Criteria andPinhaoNotEqualTo(String value) {
            addCriterion("pinhao <>", value, "pinhao");
            return this;
        }

        public Criteria andPinhaoGreaterThan(String value) {
            addCriterion("pinhao >", value, "pinhao");
            return this;
        }

        public Criteria andPinhaoGreaterThanOrEqualTo(String value) {
            addCriterion("pinhao >=", value, "pinhao");
            return this;
        }

        public Criteria andPinhaoLessThan(String value) {
            addCriterion("pinhao <", value, "pinhao");
            return this;
        }

        public Criteria andPinhaoLessThanOrEqualTo(String value) {
            addCriterion("pinhao <=", value, "pinhao");
            return this;
        }

        public Criteria andPinhaoLike(String value) {
            addCriterion("pinhao like", value, "pinhao");
            return this;
        }

        public Criteria andPinhaoNotLike(String value) {
            addCriterion("pinhao not like", value, "pinhao");
            return this;
        }

        public Criteria andPinhaoIn(List values) {
            addCriterion("pinhao in", values, "pinhao");
            return this;
        }

        public Criteria andPinhaoNotIn(List values) {
            addCriterion("pinhao not in", values, "pinhao");
            return this;
        }

        public Criteria andPinhaoBetween(String value1, String value2) {
            addCriterion("pinhao between", value1, value2, "pinhao");
            return this;
        }

        public Criteria andPinhaoNotBetween(String value1, String value2) {
            addCriterion("pinhao not between", value1, value2, "pinhao");
            return this;
        }

        public Criteria andTimesIsNull() {
            addCriterion("times is null");
            return this;
        }

        public Criteria andTimesIsNotNull() {
            addCriterion("times is not null");
            return this;
        }

        public Criteria andTimesEqualTo(Integer value) {
            addCriterion("times =", value, "times");
            return this;
        }

        public Criteria andTimesNotEqualTo(Integer value) {
            addCriterion("times <>", value, "times");
            return this;
        }

        public Criteria andTimesGreaterThan(Integer value) {
            addCriterion("times >", value, "times");
            return this;
        }

        public Criteria andTimesGreaterThanOrEqualTo(Integer value) {
            addCriterion("times >=", value, "times");
            return this;
        }

        public Criteria andTimesLessThan(Integer value) {
            addCriterion("times <", value, "times");
            return this;
        }

        public Criteria andTimesLessThanOrEqualTo(Integer value) {
            addCriterion("times <=", value, "times");
            return this;
        }

        public Criteria andTimesIn(List values) {
            addCriterion("times in", values, "times");
            return this;
        }

        public Criteria andTimesNotIn(List values) {
            addCriterion("times not in", values, "times");
            return this;
        }

        public Criteria andTimesBetween(Integer value1, Integer value2) {
            addCriterion("times between", value1, value2, "times");
            return this;
        }

        public Criteria andTimesNotBetween(Integer value1, Integer value2) {
            addCriterion("times not between", value1, value2, "times");
            return this;
        }

        public Criteria andPnumberIsNull() {
            addCriterion("pnumber is null");
            return this;
        }

        public Criteria andPnumberIsNotNull() {
            addCriterion("pnumber is not null");
            return this;
        }

        public Criteria andPnumberEqualTo(String value) {
            addCriterion("pnumber =", value, "pnumber");
            return this;
        }

        public Criteria andPnumberNotEqualTo(String value) {
            addCriterion("pnumber <>", value, "pnumber");
            return this;
        }

        public Criteria andPnumberGreaterThan(String value) {
            addCriterion("pnumber >", value, "pnumber");
            return this;
        }

        public Criteria andPnumberGreaterThanOrEqualTo(String value) {
            addCriterion("pnumber >=", value, "pnumber");
            return this;
        }

        public Criteria andPnumberLessThan(String value) {
            addCriterion("pnumber <", value, "pnumber");
            return this;
        }

        public Criteria andPnumberLessThanOrEqualTo(String value) {
            addCriterion("pnumber <=", value, "pnumber");
            return this;
        }

        public Criteria andPnumberLike(String value) {
            addCriterion("pnumber like", value, "pnumber");
            return this;
        }

        public Criteria andPnumberNotLike(String value) {
            addCriterion("pnumber not like", value, "pnumber");
            return this;
        }

        public Criteria andPnumberIn(List values) {
            addCriterion("pnumber in", values, "pnumber");
            return this;
        }

        public Criteria andPnumberNotIn(List values) {
            addCriterion("pnumber not in", values, "pnumber");
            return this;
        }

        public Criteria andPnumberBetween(String value1, String value2) {
            addCriterion("pnumber between", value1, value2, "pnumber");
            return this;
        }

        public Criteria andPnumberNotBetween(String value1, String value2) {
            addCriterion("pnumber not between", value1, value2, "pnumber");
            return this;
        }

        public Criteria andChecknumberIsNull() {
            addCriterion("checknumber is null");
            return this;
        }

        public Criteria andChecknumberIsNotNull() {
            addCriterion("checknumber is not null");
            return this;
        }

        public Criteria andChecknumberEqualTo(String value) {
            addCriterion("checknumber =", value, "checknumber");
            return this;
        }

        public Criteria andChecknumberNotEqualTo(String value) {
            addCriterion("checknumber <>", value, "checknumber");
            return this;
        }

        public Criteria andChecknumberGreaterThan(String value) {
            addCriterion("checknumber >", value, "checknumber");
            return this;
        }

        public Criteria andChecknumberGreaterThanOrEqualTo(String value) {
            addCriterion("checknumber >=", value, "checknumber");
            return this;
        }

        public Criteria andChecknumberLessThan(String value) {
            addCriterion("checknumber <", value, "checknumber");
            return this;
        }

        public Criteria andChecknumberLessThanOrEqualTo(String value) {
            addCriterion("checknumber <=", value, "checknumber");
            return this;
        }

        public Criteria andChecknumberLike(String value) {
            addCriterion("checknumber like", value, "checknumber");
            return this;
        }

        public Criteria andChecknumberNotLike(String value) {
            addCriterion("checknumber not like", value, "checknumber");
            return this;
        }

        public Criteria andChecknumberIn(List values) {
            addCriterion("checknumber in", values, "checknumber");
            return this;
        }

        public Criteria andChecknumberNotIn(List values) {
            addCriterion("checknumber not in", values, "checknumber");
            return this;
        }

        public Criteria andChecknumberBetween(String value1, String value2) {
            addCriterion("checknumber between", value1, value2, "checknumber");
            return this;
        }

        public Criteria andChecknumberNotBetween(String value1, String value2) {
            addCriterion("checknumber not between", value1, value2, "checknumber");
            return this;
        }

        public Criteria andSupplynameIsNull() {
            addCriterion("supplyname is null");
            return this;
        }

        public Criteria andSupplynameIsNotNull() {
            addCriterion("supplyname is not null");
            return this;
        }

        public Criteria andSupplynameEqualTo(String value) {
            addCriterion("supplyname =", value, "supplyname");
            return this;
        }

        public Criteria andSupplynameNotEqualTo(String value) {
            addCriterion("supplyname <>", value, "supplyname");
            return this;
        }

        public Criteria andSupplynameGreaterThan(String value) {
            addCriterion("supplyname >", value, "supplyname");
            return this;
        }

        public Criteria andSupplynameGreaterThanOrEqualTo(String value) {
            addCriterion("supplyname >=", value, "supplyname");
            return this;
        }

        public Criteria andSupplynameLessThan(String value) {
            addCriterion("supplyname <", value, "supplyname");
            return this;
        }

        public Criteria andSupplynameLessThanOrEqualTo(String value) {
            addCriterion("supplyname <=", value, "supplyname");
            return this;
        }

        public Criteria andSupplynameLike(String value) {
            addCriterion("supplyname like", value, "supplyname");
            return this;
        }

        public Criteria andSupplynameNotLike(String value) {
            addCriterion("supplyname not like", value, "supplyname");
            return this;
        }

        public Criteria andSupplynameIn(List values) {
            addCriterion("supplyname in", values, "supplyname");
            return this;
        }

        public Criteria andSupplynameNotIn(List values) {
            addCriterion("supplyname not in", values, "supplyname");
            return this;
        }

        public Criteria andSupplynameBetween(String value1, String value2) {
            addCriterion("supplyname between", value1, value2, "supplyname");
            return this;
        }

        public Criteria andSupplynameNotBetween(String value1, String value2) {
            addCriterion("supplyname not between", value1, value2, "supplyname");
            return this;
        }

        public Criteria andLocationcityIsNull() {
            addCriterion("locationcity is null");
            return this;
        }

        public Criteria andLocationcityIsNotNull() {
            addCriterion("locationcity is not null");
            return this;
        }

        public Criteria andLocationcityEqualTo(String value) {
            addCriterion("locationcity =", value, "locationcity");
            return this;
        }

        public Criteria andLocationcityNotEqualTo(String value) {
            addCriterion("locationcity <>", value, "locationcity");
            return this;
        }

        public Criteria andLocationcityGreaterThan(String value) {
            addCriterion("locationcity >", value, "locationcity");
            return this;
        }

        public Criteria andLocationcityGreaterThanOrEqualTo(String value) {
            addCriterion("locationcity >=", value, "locationcity");
            return this;
        }

        public Criteria andLocationcityLessThan(String value) {
            addCriterion("locationcity <", value, "locationcity");
            return this;
        }

        public Criteria andLocationcityLessThanOrEqualTo(String value) {
            addCriterion("locationcity <=", value, "locationcity");
            return this;
        }

        public Criteria andLocationcityLike(String value) {
            addCriterion("locationcity like", value, "locationcity");
            return this;
        }

        public Criteria andLocationcityNotLike(String value) {
            addCriterion("locationcity not like", value, "locationcity");
            return this;
        }

        public Criteria andLocationcityIn(List values) {
            addCriterion("locationcity in", values, "locationcity");
            return this;
        }

        public Criteria andLocationcityNotIn(List values) {
            addCriterion("locationcity not in", values, "locationcity");
            return this;
        }

        public Criteria andLocationcityBetween(String value1, String value2) {
            addCriterion("locationcity between", value1, value2, "locationcity");
            return this;
        }

        public Criteria andLocationcityNotBetween(String value1, String value2) {
            addCriterion("locationcity not between", value1, value2, "locationcity");
            return this;
        }

        public Criteria andDetailchandiIsNull() {
            addCriterion("detailchandi is null");
            return this;
        }

        public Criteria andDetailchandiIsNotNull() {
            addCriterion("detailchandi is not null");
            return this;
        }

        public Criteria andDetailchandiEqualTo(String value) {
            addCriterion("detailchandi =", value, "detailchandi");
            return this;
        }

        public Criteria andDetailchandiNotEqualTo(String value) {
            addCriterion("detailchandi <>", value, "detailchandi");
            return this;
        }

        public Criteria andDetailchandiGreaterThan(String value) {
            addCriterion("detailchandi >", value, "detailchandi");
            return this;
        }

        public Criteria andDetailchandiGreaterThanOrEqualTo(String value) {
            addCriterion("detailchandi >=", value, "detailchandi");
            return this;
        }

        public Criteria andDetailchandiLessThan(String value) {
            addCriterion("detailchandi <", value, "detailchandi");
            return this;
        }

        public Criteria andDetailchandiLessThanOrEqualTo(String value) {
            addCriterion("detailchandi <=", value, "detailchandi");
            return this;
        }

        public Criteria andDetailchandiLike(String value) {
            addCriterion("detailchandi like", value, "detailchandi");
            return this;
        }

        public Criteria andDetailchandiNotLike(String value) {
            addCriterion("detailchandi not like", value, "detailchandi");
            return this;
        }

        public Criteria andDetailchandiIn(List values) {
            addCriterion("detailchandi in", values, "detailchandi");
            return this;
        }

        public Criteria andDetailchandiNotIn(List values) {
            addCriterion("detailchandi not in", values, "detailchandi");
            return this;
        }

        public Criteria andDetailchandiBetween(String value1, String value2) {
            addCriterion("detailchandi between", value1, value2, "detailchandi");
            return this;
        }

        public Criteria andDetailchandiNotBetween(String value1, String value2) {
            addCriterion("detailchandi not between", value1, value2, "detailchandi");
            return this;
        }

        public Criteria andGuigeIsNull() {
            addCriterion("guige is null");
            return this;
        }

        public Criteria andGuigeIsNotNull() {
            addCriterion("guige is not null");
            return this;
        }

        public Criteria andGuigeEqualTo(String value) {
            addCriterion("guige =", value, "guige");
            return this;
        }

        public Criteria andGuigeNotEqualTo(String value) {
            addCriterion("guige <>", value, "guige");
            return this;
        }

        public Criteria andGuigeGreaterThan(String value) {
            addCriterion("guige >", value, "guige");
            return this;
        }

        public Criteria andGuigeGreaterThanOrEqualTo(String value) {
            addCriterion("guige >=", value, "guige");
            return this;
        }

        public Criteria andGuigeLessThan(String value) {
            addCriterion("guige <", value, "guige");
            return this;
        }

        public Criteria andGuigeLessThanOrEqualTo(String value) {
            addCriterion("guige <=", value, "guige");
            return this;
        }

        public Criteria andGuigeLike(String value) {
            addCriterion("guige like", value, "guige");
            return this;
        }

        public Criteria andGuigeNotLike(String value) {
            addCriterion("guige not like", value, "guige");
            return this;
        }

        public Criteria andGuigeIn(List values) {
            addCriterion("guige in", values, "guige");
            return this;
        }

        public Criteria andGuigeNotIn(List values) {
            addCriterion("guige not in", values, "guige");
            return this;
        }

        public Criteria andGuigeBetween(String value1, String value2) {
            addCriterion("guige between", value1, value2, "guige");
            return this;
        }

        public Criteria andGuigeNotBetween(String value1, String value2) {
            addCriterion("guige not between", value1, value2, "guige");
            return this;
        }

        public Criteria andJianshuIsNull() {
            addCriterion("jianshu is null");
            return this;
        }

        public Criteria andJianshuIsNotNull() {
            addCriterion("jianshu is not null");
            return this;
        }

        public Criteria andJianshuEqualTo(Integer value) {
            addCriterion("jianshu =", value, "jianshu");
            return this;
        }

        public Criteria andJianshuNotEqualTo(Integer value) {
            addCriterion("jianshu <>", value, "jianshu");
            return this;
        }

        public Criteria andJianshuGreaterThan(Integer value) {
            addCriterion("jianshu >", value, "jianshu");
            return this;
        }

        public Criteria andJianshuGreaterThanOrEqualTo(Integer value) {
            addCriterion("jianshu >=", value, "jianshu");
            return this;
        }

        public Criteria andJianshuLessThan(Integer value) {
            addCriterion("jianshu <", value, "jianshu");
            return this;
        }

        public Criteria andJianshuLessThanOrEqualTo(Integer value) {
            addCriterion("jianshu <=", value, "jianshu");
            return this;
        }

        public Criteria andJianshuIn(List values) {
            addCriterion("jianshu in", values, "jianshu");
            return this;
        }

        public Criteria andJianshuNotIn(List values) {
            addCriterion("jianshu not in", values, "jianshu");
            return this;
        }

        public Criteria andJianshuBetween(Integer value1, Integer value2) {
            addCriterion("jianshu between", value1, value2, "jianshu");
            return this;
        }

        public Criteria andJianshuNotBetween(Integer value1, Integer value2) {
            addCriterion("jianshu not between", value1, value2, "jianshu");
            return this;
        }

        public Criteria andShuliangIsNull() {
            addCriterion("shuliang is null");
            return this;
        }

        public Criteria andShuliangIsNotNull() {
            addCriterion("shuliang is not null");
            return this;
        }

        public Criteria andShuliangEqualTo(String value) {
            addCriterion("shuliang =", value, "shuliang");
            return this;
        }

        public Criteria andShuliangNotEqualTo(String value) {
            addCriterion("shuliang <>", value, "shuliang");
            return this;
        }

        public Criteria andShuliangGreaterThan(String value) {
            addCriterion("shuliang >", value, "shuliang");
            return this;
        }

        public Criteria andShuliangGreaterThanOrEqualTo(String value) {
            addCriterion("shuliang >=", value, "shuliang");
            return this;
        }

        public Criteria andShuliangLessThan(String value) {
            addCriterion("shuliang <", value, "shuliang");
            return this;
        }

        public Criteria andShuliangLessThanOrEqualTo(String value) {
            addCriterion("shuliang <=", value, "shuliang");
            return this;
        }

        public Criteria andShuliangLike(String value) {
            addCriterion("shuliang like", value, "shuliang");
            return this;
        }

        public Criteria andShuliangNotLike(String value) {
            addCriterion("shuliang not like", value, "shuliang");
            return this;
        }

        public Criteria andShuliangIn(List values) {
            addCriterion("shuliang in", values, "shuliang");
            return this;
        }

        public Criteria andShuliangNotIn(List values) {
            addCriterion("shuliang not in", values, "shuliang");
            return this;
        }

        public Criteria andShuliangBetween(String value1, String value2) {
            addCriterion("shuliang between", value1, value2, "shuliang");
            return this;
        }

        public Criteria andShuliangNotBetween(String value1, String value2) {
            addCriterion("shuliang not between", value1, value2, "shuliang");
            return this;
        }

        public Criteria andFromdateIsNull() {
            addCriterion("fromdate is null");
            return this;
        }

        public Criteria andFromdateIsNotNull() {
            addCriterion("fromdate is not null");
            return this;
        }

        public Criteria andFromdateEqualTo(String value) {
            addCriterion("fromdate =", value, "fromdate");
            return this;
        }

        public Criteria andFromdateNotEqualTo(String value) {
            addCriterion("fromdate <>", value, "fromdate");
            return this;
        }

        public Criteria andFromdateGreaterThan(String value) {
            addCriterion("fromdate >", value, "fromdate");
            return this;
        }

        public Criteria andFromdateGreaterThanOrEqualTo(String value) {
            addCriterion("fromdate >=", value, "fromdate");
            return this;
        }

        public Criteria andFromdateLessThan(String value) {
            addCriterion("fromdate <", value, "fromdate");
            return this;
        }

        public Criteria andFromdateLessThanOrEqualTo(String value) {
            addCriterion("fromdate <=", value, "fromdate");
            return this;
        }

        public Criteria andFromdateLike(String value) {
            addCriterion("fromdate like", value, "fromdate");
            return this;
        }

        public Criteria andFromdateNotLike(String value) {
            addCriterion("fromdate not like", value, "fromdate");
            return this;
        }

        public Criteria andFromdateIn(List values) {
            addCriterion("fromdate in", values, "fromdate");
            return this;
        }

        public Criteria andFromdateNotIn(List values) {
            addCriterion("fromdate not in", values, "fromdate");
            return this;
        }

        public Criteria andFromdateBetween(String value1, String value2) {
            addCriterion("fromdate between", value1, value2, "fromdate");
            return this;
        }

        public Criteria andFromdateNotBetween(String value1, String value2) {
            addCriterion("fromdate not between", value1, value2, "fromdate");
            return this;
        }

        public Criteria andDemodateIsNull() {
            addCriterion("demodate is null");
            return this;
        }

        public Criteria andDemodateIsNotNull() {
            addCriterion("demodate is not null");
            return this;
        }

        public Criteria andDemodateEqualTo(String value) {
            addCriterion("demodate =", value, "demodate");
            return this;
        }

        public Criteria andDemodateNotEqualTo(String value) {
            addCriterion("demodate <>", value, "demodate");
            return this;
        }

        public Criteria andDemodateGreaterThan(String value) {
            addCriterion("demodate >", value, "demodate");
            return this;
        }

        public Criteria andDemodateGreaterThanOrEqualTo(String value) {
            addCriterion("demodate >=", value, "demodate");
            return this;
        }

        public Criteria andDemodateLessThan(String value) {
            addCriterion("demodate <", value, "demodate");
            return this;
        }

        public Criteria andDemodateLessThanOrEqualTo(String value) {
            addCriterion("demodate <=", value, "demodate");
            return this;
        }

        public Criteria andDemodateLike(String value) {
            addCriterion("demodate like", value, "demodate");
            return this;
        }

        public Criteria andDemodateNotLike(String value) {
            addCriterion("demodate not like", value, "demodate");
            return this;
        }

        public Criteria andDemodateIn(List values) {
            addCriterion("demodate in", values, "demodate");
            return this;
        }

        public Criteria andDemodateNotIn(List values) {
            addCriterion("demodate not in", values, "demodate");
            return this;
        }

        public Criteria andDemodateBetween(String value1, String value2) {
            addCriterion("demodate between", value1, value2, "demodate");
            return this;
        }

        public Criteria andDemodateNotBetween(String value1, String value2) {
            addCriterion("demodate not between", value1, value2, "demodate");
            return this;
        }

        public Criteria andFangxingdateIsNull() {
            addCriterion("fangxingdate is null");
            return this;
        }

        public Criteria andFangxingdateIsNotNull() {
            addCriterion("fangxingdate is not null");
            return this;
        }

        public Criteria andFangxingdateEqualTo(String value) {
            addCriterion("fangxingdate =", value, "fangxingdate");
            return this;
        }

        public Criteria andFangxingdateNotEqualTo(String value) {
            addCriterion("fangxingdate <>", value, "fangxingdate");
            return this;
        }

        public Criteria andFangxingdateGreaterThan(String value) {
            addCriterion("fangxingdate >", value, "fangxingdate");
            return this;
        }

        public Criteria andFangxingdateGreaterThanOrEqualTo(String value) {
            addCriterion("fangxingdate >=", value, "fangxingdate");
            return this;
        }

        public Criteria andFangxingdateLessThan(String value) {
            addCriterion("fangxingdate <", value, "fangxingdate");
            return this;
        }

        public Criteria andFangxingdateLessThanOrEqualTo(String value) {
            addCriterion("fangxingdate <=", value, "fangxingdate");
            return this;
        }

        public Criteria andFangxingdateLike(String value) {
            addCriterion("fangxingdate like", value, "fangxingdate");
            return this;
        }

        public Criteria andFangxingdateNotLike(String value) {
            addCriterion("fangxingdate not like", value, "fangxingdate");
            return this;
        }

        public Criteria andFangxingdateIn(List values) {
            addCriterion("fangxingdate in", values, "fangxingdate");
            return this;
        }

        public Criteria andFangxingdateNotIn(List values) {
            addCriterion("fangxingdate not in", values, "fangxingdate");
            return this;
        }

        public Criteria andFangxingdateBetween(String value1, String value2) {
            addCriterion("fangxingdate between", value1, value2, "fangxingdate");
            return this;
        }

        public Criteria andFangxingdateNotBetween(String value1, String value2) {
            addCriterion("fangxingdate not between", value1, value2, "fangxingdate");
            return this;
        }

        public Criteria andCheckresultIsNull() {
            addCriterion("checkresult is null");
            return this;
        }

        public Criteria andCheckresultIsNotNull() {
            addCriterion("checkresult is not null");
            return this;
        }

        public Criteria andCheckresultEqualTo(String value) {
            addCriterion("checkresult =", value, "checkresult");
            return this;
        }

        public Criteria andCheckresultNotEqualTo(String value) {
            addCriterion("checkresult <>", value, "checkresult");
            return this;
        }

        public Criteria andCheckresultGreaterThan(String value) {
            addCriterion("checkresult >", value, "checkresult");
            return this;
        }

        public Criteria andCheckresultGreaterThanOrEqualTo(String value) {
            addCriterion("checkresult >=", value, "checkresult");
            return this;
        }

        public Criteria andCheckresultLessThan(String value) {
            addCriterion("checkresult <", value, "checkresult");
            return this;
        }

        public Criteria andCheckresultLessThanOrEqualTo(String value) {
            addCriterion("checkresult <=", value, "checkresult");
            return this;
        }

        public Criteria andCheckresultLike(String value) {
            addCriterion("checkresult like", value, "checkresult");
            return this;
        }

        public Criteria andCheckresultNotLike(String value) {
            addCriterion("checkresult not like", value, "checkresult");
            return this;
        }

        public Criteria andCheckresultIn(List values) {
            addCriterion("checkresult in", values, "checkresult");
            return this;
        }

        public Criteria andCheckresultNotIn(List values) {
            addCriterion("checkresult not in", values, "checkresult");
            return this;
        }

        public Criteria andCheckresultBetween(String value1, String value2) {
            addCriterion("checkresult between", value1, value2, "checkresult");
            return this;
        }

        public Criteria andCheckresultNotBetween(String value1, String value2) {
            addCriterion("checkresult not between", value1, value2, "checkresult");
            return this;
        }

        public Criteria andSenddateIsNull() {
            addCriterion("sendDate is null");
            return this;
        }

        public Criteria andSenddateIsNotNull() {
            addCriterion("sendDate is not null");
            return this;
        }

        public Criteria andSenddateEqualTo(String value) {
            addCriterion("sendDate =", value, "senddate");
            return this;
        }

        public Criteria andSenddateNotEqualTo(String value) {
            addCriterion("sendDate <>", value, "senddate");
            return this;
        }

        public Criteria andSenddateGreaterThan(String value) {
            addCriterion("sendDate >", value, "senddate");
            return this;
        }

        public Criteria andSenddateGreaterThanOrEqualTo(String value) {
            addCriterion("sendDate >=", value, "senddate");
            return this;
        }

        public Criteria andSenddateLessThan(String value) {
            addCriterion("sendDate <", value, "senddate");
            return this;
        }

        public Criteria andSenddateLessThanOrEqualTo(String value) {
            addCriterion("sendDate <=", value, "senddate");
            return this;
        }

        public Criteria andSenddateLike(String value) {
            addCriterion("sendDate like", value, "senddate");
            return this;
        }

        public Criteria andSenddateNotLike(String value) {
            addCriterion("sendDate not like", value, "senddate");
            return this;
        }

        public Criteria andSenddateIn(List values) {
            addCriterion("sendDate in", values, "senddate");
            return this;
        }

        public Criteria andSenddateNotIn(List values) {
            addCriterion("sendDate not in", values, "senddate");
            return this;
        }

        public Criteria andSenddateBetween(String value1, String value2) {
            addCriterion("sendDate between", value1, value2, "senddate");
            return this;
        }

        public Criteria andSenddateNotBetween(String value1, String value2) {
            addCriterion("sendDate not between", value1, value2, "senddate");
            return this;
        }

        public Criteria andReceivelocationIsNull() {
            addCriterion("receivelocation is null");
            return this;
        }

        public Criteria andReceivelocationIsNotNull() {
            addCriterion("receivelocation is not null");
            return this;
        }

        public Criteria andReceivelocationEqualTo(String value) {
            addCriterion("receivelocation =", value, "receivelocation");
            return this;
        }

        public Criteria andReceivelocationNotEqualTo(String value) {
            addCriterion("receivelocation <>", value, "receivelocation");
            return this;
        }

        public Criteria andReceivelocationGreaterThan(String value) {
            addCriterion("receivelocation >", value, "receivelocation");
            return this;
        }

        public Criteria andReceivelocationGreaterThanOrEqualTo(String value) {
            addCriterion("receivelocation >=", value, "receivelocation");
            return this;
        }

        public Criteria andReceivelocationLessThan(String value) {
            addCriterion("receivelocation <", value, "receivelocation");
            return this;
        }

        public Criteria andReceivelocationLessThanOrEqualTo(String value) {
            addCriterion("receivelocation <=", value, "receivelocation");
            return this;
        }

        public Criteria andReceivelocationLike(String value) {
            addCriterion("receivelocation like", value, "receivelocation");
            return this;
        }

        public Criteria andReceivelocationNotLike(String value) {
            addCriterion("receivelocation not like", value, "receivelocation");
            return this;
        }

        public Criteria andReceivelocationIn(List values) {
            addCriterion("receivelocation in", values, "receivelocation");
            return this;
        }

        public Criteria andReceivelocationNotIn(List values) {
            addCriterion("receivelocation not in", values, "receivelocation");
            return this;
        }

        public Criteria andReceivelocationBetween(String value1, String value2) {
            addCriterion("receivelocation between", value1, value2, "receivelocation");
            return this;
        }

        public Criteria andReceivelocationNotBetween(String value1, String value2) {
            addCriterion("receivelocation not between", value1, value2, "receivelocation");
            return this;
        }

        public Criteria andYuanliaodaodateIsNull() {
            addCriterion("yuanliaodaodate is null");
            return this;
        }

        public Criteria andYuanliaodaodateIsNotNull() {
            addCriterion("yuanliaodaodate is not null");
            return this;
        }

        public Criteria andYuanliaodaodateEqualTo(String value) {
            addCriterion("yuanliaodaodate =", value, "yuanliaodaodate");
            return this;
        }

        public Criteria andYuanliaodaodateNotEqualTo(String value) {
            addCriterion("yuanliaodaodate <>", value, "yuanliaodaodate");
            return this;
        }

        public Criteria andYuanliaodaodateGreaterThan(String value) {
            addCriterion("yuanliaodaodate >", value, "yuanliaodaodate");
            return this;
        }

        public Criteria andYuanliaodaodateGreaterThanOrEqualTo(String value) {
            addCriterion("yuanliaodaodate >=", value, "yuanliaodaodate");
            return this;
        }

        public Criteria andYuanliaodaodateLessThan(String value) {
            addCriterion("yuanliaodaodate <", value, "yuanliaodaodate");
            return this;
        }

        public Criteria andYuanliaodaodateLessThanOrEqualTo(String value) {
            addCriterion("yuanliaodaodate <=", value, "yuanliaodaodate");
            return this;
        }

        public Criteria andYuanliaodaodateLike(String value) {
            addCriterion("yuanliaodaodate like", value, "yuanliaodaodate");
            return this;
        }

        public Criteria andYuanliaodaodateNotLike(String value) {
            addCriterion("yuanliaodaodate not like", value, "yuanliaodaodate");
            return this;
        }

        public Criteria andYuanliaodaodateIn(List values) {
            addCriterion("yuanliaodaodate in", values, "yuanliaodaodate");
            return this;
        }

        public Criteria andYuanliaodaodateNotIn(List values) {
            addCriterion("yuanliaodaodate not in", values, "yuanliaodaodate");
            return this;
        }

        public Criteria andYuanliaodaodateBetween(String value1, String value2) {
            addCriterion("yuanliaodaodate between", value1, value2, "yuanliaodaodate");
            return this;
        }

        public Criteria andYuanliaodaodateNotBetween(String value1, String value2) {
            addCriterion("yuanliaodaodate not between", value1, value2, "yuanliaodaodate");
            return this;
        }

        public Criteria andDaodaozhongliangIsNull() {
            addCriterion("daodaozhongliang is null");
            return this;
        }

        public Criteria andDaodaozhongliangIsNotNull() {
            addCriterion("daodaozhongliang is not null");
            return this;
        }

        public Criteria andDaodaozhongliangEqualTo(String value) {
            addCriterion("daodaozhongliang =", value, "daodaozhongliang");
            return this;
        }

        public Criteria andDaodaozhongliangNotEqualTo(String value) {
            addCriterion("daodaozhongliang <>", value, "daodaozhongliang");
            return this;
        }

        public Criteria andDaodaozhongliangGreaterThan(String value) {
            addCriterion("daodaozhongliang >", value, "daodaozhongliang");
            return this;
        }

        public Criteria andDaodaozhongliangGreaterThanOrEqualTo(String value) {
            addCriterion("daodaozhongliang >=", value, "daodaozhongliang");
            return this;
        }

        public Criteria andDaodaozhongliangLessThan(String value) {
            addCriterion("daodaozhongliang <", value, "daodaozhongliang");
            return this;
        }

        public Criteria andDaodaozhongliangLessThanOrEqualTo(String value) {
            addCriterion("daodaozhongliang <=", value, "daodaozhongliang");
            return this;
        }

        public Criteria andDaodaozhongliangLike(String value) {
            addCriterion("daodaozhongliang like", value, "daodaozhongliang");
            return this;
        }

        public Criteria andDaodaozhongliangNotLike(String value) {
            addCriterion("daodaozhongliang not like", value, "daodaozhongliang");
            return this;
        }

        public Criteria andDaodaozhongliangIn(List values) {
            addCriterion("daodaozhongliang in", values, "daodaozhongliang");
            return this;
        }

        public Criteria andDaodaozhongliangNotIn(List values) {
            addCriterion("daodaozhongliang not in", values, "daodaozhongliang");
            return this;
        }

        public Criteria andDaodaozhongliangBetween(String value1, String value2) {
            addCriterion("daodaozhongliang between", value1, value2, "daodaozhongliang");
            return this;
        }

        public Criteria andDaodaozhongliangNotBetween(String value1, String value2) {
            addCriterion("daodaozhongliang not between", value1, value2, "daodaozhongliang");
            return this;
        }

        public Criteria andBeizhuIsNull() {
            addCriterion("beizhu is null");
            return this;
        }

        public Criteria andBeizhuIsNotNull() {
            addCriterion("beizhu is not null");
            return this;
        }

        public Criteria andBeizhuEqualTo(String value) {
            addCriterion("beizhu =", value, "beizhu");
            return this;
        }

        public Criteria andBeizhuNotEqualTo(String value) {
            addCriterion("beizhu <>", value, "beizhu");
            return this;
        }

        public Criteria andBeizhuGreaterThan(String value) {
            addCriterion("beizhu >", value, "beizhu");
            return this;
        }

        public Criteria andBeizhuGreaterThanOrEqualTo(String value) {
            addCriterion("beizhu >=", value, "beizhu");
            return this;
        }

        public Criteria andBeizhuLessThan(String value) {
            addCriterion("beizhu <", value, "beizhu");
            return this;
        }

        public Criteria andBeizhuLessThanOrEqualTo(String value) {
            addCriterion("beizhu <=", value, "beizhu");
            return this;
        }

        public Criteria andBeizhuLike(String value) {
            addCriterion("beizhu like", value, "beizhu");
            return this;
        }

        public Criteria andBeizhuNotLike(String value) {
            addCriterion("beizhu not like", value, "beizhu");
            return this;
        }

        public Criteria andBeizhuIn(List values) {
            addCriterion("beizhu in", values, "beizhu");
            return this;
        }

        public Criteria andBeizhuNotIn(List values) {
            addCriterion("beizhu not in", values, "beizhu");
            return this;
        }

        public Criteria andBeizhuBetween(String value1, String value2) {
            addCriterion("beizhu between", value1, value2, "beizhu");
            return this;
        }

        public Criteria andBeizhuNotBetween(String value1, String value2) {
            addCriterion("beizhu not between", value1, value2, "beizhu");
            return this;
        }

        public Criteria andSendaddressIsNull() {
            addCriterion("sendaddress is null");
            return this;
        }

        public Criteria andSendaddressIsNotNull() {
            addCriterion("sendaddress is not null");
            return this;
        }

        public Criteria andSendaddressEqualTo(String value) {
            addCriterion("sendaddress =", value, "sendaddress");
            return this;
        }

        public Criteria andSendaddressNotEqualTo(String value) {
            addCriterion("sendaddress <>", value, "sendaddress");
            return this;
        }

        public Criteria andSendaddressGreaterThan(String value) {
            addCriterion("sendaddress >", value, "sendaddress");
            return this;
        }

        public Criteria andSendaddressGreaterThanOrEqualTo(String value) {
            addCriterion("sendaddress >=", value, "sendaddress");
            return this;
        }

        public Criteria andSendaddressLessThan(String value) {
            addCriterion("sendaddress <", value, "sendaddress");
            return this;
        }

        public Criteria andSendaddressLessThanOrEqualTo(String value) {
            addCriterion("sendaddress <=", value, "sendaddress");
            return this;
        }

        public Criteria andSendaddressLike(String value) {
            addCriterion("sendaddress like", value, "sendaddress");
            return this;
        }

        public Criteria andSendaddressNotLike(String value) {
            addCriterion("sendaddress not like", value, "sendaddress");
            return this;
        }

        public Criteria andSendaddressIn(List values) {
            addCriterion("sendaddress in", values, "sendaddress");
            return this;
        }

        public Criteria andSendaddressNotIn(List values) {
            addCriterion("sendaddress not in", values, "sendaddress");
            return this;
        }

        public Criteria andSendaddressBetween(String value1, String value2) {
            addCriterion("sendaddress between", value1, value2, "sendaddress");
            return this;
        }

        public Criteria andSendaddressNotBetween(String value1, String value2) {
            addCriterion("sendaddress not between", value1, value2, "sendaddress");
            return this;
        }
    }
}