package cn.krt.zbcg.system.dao;

import cn.krt.zbcg.commons.bo.system.ShqdheadBO;
import cn.krt.zbcg.commons.bo.system.ShqdheadExample;

import java.util.List;

public interface ShqdheadDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shqdhead
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    void insert(ShqdheadBO record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shqdhead
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    int updateByPrimaryKey(ShqdheadBO record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shqdhead
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    int updateByPrimaryKeySelective(ShqdheadBO record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shqdhead
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    List selectByExample(ShqdheadExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shqdhead
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    ShqdheadBO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shqdhead
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    int deleteByExample(ShqdheadExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shqdhead
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shqdhead
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    int countByExample(ShqdheadExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shqdhead
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    int updateByExampleSelective(ShqdheadBO record, ShqdheadExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shqdhead
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    int updateByExample(ShqdheadBO record, ShqdheadExample example);
    
    public abstract List selectAll(Object paramObject);
	Object selectAllOfCount(Object obj);
    public abstract List selectAlls(Object paramObject);
    public abstract Object selectAllOfCounts(Object paramObject);
}