package cn.krt.zbcg.system.dao.impl;

import cn.krt.zbcg.commons.bo.system.StorageBO;
import cn.krt.zbcg.commons.bo.system.StorageExample;
import cn.krt.zbcg.system.dao.StorageDAO;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import org.ssi.dao.impl.BaseDaoImpl;

public class StorageDAOImpl extends BaseDaoImpl implements StorageDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table storage
     *
     * @abatorgenerated Sun Jul 21 12:52:32 CST 2013
     */
    public StorageDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table storage
     *
     * @abatorgenerated Sun Jul 21 12:52:32 CST 2013
     */
    public void insert(StorageBO record) {
        getSqlMapClientTemplate().insert("storage.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table storage
     *
     * @abatorgenerated Sun Jul 21 12:52:32 CST 2013
     */
    public int updateByPrimaryKey(StorageBO record) {
        int rows = getSqlMapClientTemplate().update("storage.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table storage
     *
     * @abatorgenerated Sun Jul 21 12:52:32 CST 2013
     */
    public int updateByPrimaryKeySelective(StorageBO record) {
        int rows = getSqlMapClientTemplate().update("storage.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table storage
     *
     * @abatorgenerated Sun Jul 21 12:52:32 CST 2013
     */
    public List selectByExample(StorageExample example) {
        List list = getSqlMapClientTemplate().queryForList("storage.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table storage
     *
     * @abatorgenerated Sun Jul 21 12:52:32 CST 2013
     */
    public StorageBO selectByPrimaryKey(Integer id) {
        StorageBO key = new StorageBO();
        key.setId(id);
        StorageBO record = (StorageBO) getSqlMapClientTemplate().queryForObject("storage.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }
    public Object  selectDaiyanshuliang(){
    	Object ob = getSqlMapClientTemplate().queryForObject("storage.abatorgenerated_daiyanshuliangsum");
		return ob;
    }
    
    public List selectDaiyanPhao(){
    	List list = queryList("storage.abatorgenerated_daiyanphao");
		return list;
    }
    
    public Object  selectBuhegeshuliang(){
    	Object ob = getSqlMapClientTemplate().queryForObject("storage.abatorgenerated_buhegeshuliangsum");
		return ob;
    }
    
    public List  selectBuhege(){
    	List list = queryList("storage.abatorgenerated_buhege");
		return list;
    }
    
    
	public List selectAll(Object obj) {
		List list = queryList("storage.selectAll", obj);
		return list;
	}

	public List selectAlls(Object obj) {
		List list = queryList("storage.selectAlls", obj);
		return list;
	}

	public Object selectAllOfCount(Object obj) {
		Object o = queryData("storage.selectAllOfCount", obj);
		return o;
	}
	
	public Object selectAllOfCounts(Object obj) {
		Object o = queryData("storage.selectAllOfCounts", obj);
		return o;
	}

    public StorageBO selectByCheckresult(String checkResult) {
        StorageBO key = new StorageBO();
        key.setCheckresult(checkResult);
        StorageBO record = (StorageBO) getSqlMapClientTemplate().queryForObject("storage.abatorgenerated_selectByCheckresult", checkResult);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table storage
     *
     * @abatorgenerated Sun Jul 21 12:52:32 CST 2013
     */
    public int deleteByExample(StorageExample example) {
        int rows = getSqlMapClientTemplate().delete("storage.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table storage
     *
     * @abatorgenerated Sun Jul 21 12:52:32 CST 2013
     */
    public int deleteByPrimaryKey(Integer id) {
        StorageBO key = new StorageBO();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("storage.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table storage
     *
     * @abatorgenerated Sun Jul 21 12:52:32 CST 2013
     */
    public int countByExample(StorageExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("storage.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table storage
     *
     * @abatorgenerated Sun Jul 21 12:52:32 CST 2013
     */
    public int updateByExampleSelective(StorageBO record, StorageExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("storage.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table storage
     *
     * @abatorgenerated Sun Jul 21 12:52:32 CST 2013
     */
    public int updateByExample(StorageBO record, StorageExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("storage.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table storage
     *
     * @abatorgenerated Sun Jul 21 12:52:32 CST 2013
     */
    private static class UpdateByExampleParms extends StorageExample {
        private Object record;

        public UpdateByExampleParms(Object record, StorageExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	@Override
	public Object queryData(StorageBO key) {
	    Object record = queryData("storage.abatorgenerated_selectByPrimaryKey", key);
	     return (StorageBO) record;
	}
}