package cn.krt.zbcg.system.dao;

import cn.krt.zbcg.commons.bo.system.FapiaoinfoBO;
import cn.krt.zbcg.commons.bo.system.FukuandetailBO;
import cn.krt.zbcg.commons.bo.system.FukuandetailExample;

import java.util.List;

public interface IFukuandetailDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table fukuandetail
     *
     * @abatorgenerated Wed Aug 14 22:01:38 CST 2013
     */
    void insert(FukuandetailBO record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table fukuandetail
     *
     * @abatorgenerated Wed Aug 14 22:01:38 CST 2013
     */
    int updateByPrimaryKey(FukuandetailBO record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table fukuandetail
     *
     * @abatorgenerated Wed Aug 14 22:01:38 CST 2013
     */
    int updateByPrimaryKeySelective(FukuandetailBO record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table fukuandetail
     *
     * @abatorgenerated Wed Aug 14 22:01:38 CST 2013
     */
    List selectByExample(FukuandetailExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table fukuandetail
     *
     * @abatorgenerated Wed Aug 14 22:01:38 CST 2013
     */
    FukuandetailBO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table fukuandetail
     *
     * @abatorgenerated Wed Aug 14 22:01:38 CST 2013
     */
    int deleteByExample(FukuandetailExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table fukuandetail
     *
     * @abatorgenerated Wed Aug 14 22:01:38 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table fukuandetail
     *
     * @abatorgenerated Wed Aug 14 22:01:38 CST 2013
     */
    int countByExample(FukuandetailExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table fukuandetail
     *
     * @abatorgenerated Wed Aug 14 22:01:38 CST 2013
     */
    int updateByExampleSelective(FukuandetailBO record, FukuandetailExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table fukuandetail
     *
     * @abatorgenerated Wed Aug 14 22:01:38 CST 2013
     */
    int updateByExample(FukuandetailBO record, FukuandetailExample example);

	List selectAll(Object paramObject);

	Object selectAllOfCounts(Object paramObject);

	List selectAlls(Object paramObject);

	Object selectAllOfCount(Object obj);

	FukuandetailBO queryData(FukuandetailBO key);

	int update(FukuandetailBO record) throws Exception;


}