package cn.krt.zbcg.system.web.form;

import org.ssi.struts.actionform.BaseForm;

import cn.krt.zbcg.commons.bo.system.MedicineBO;
import cn.krt.zbcg.commons.bo.system.StorageBO;

public class StorageForm   extends BaseForm{
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column storage.id
     *
     * @abatorgenerated Sun Jul 21 12:52:32 CST 2013
     */
	
	private StorageBO storageBO = new StorageBO();
	
    public StorageBO getStorageBO() {
		return storageBO;
	}

	public void setStorageBO(StorageBO storageBO) {
		this.storageBO = storageBO;
	}


}