package cn.krt.zbcg.system.dao;

import cn.krt.zbcg.commons.bo.system.StorageBO;
import cn.krt.zbcg.commons.bo.system.StorageExample;

import java.util.List;

public interface StorageDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table storage
     *
     * @abatorgenerated Sun Jul 21 12:52:32 CST 2013
     */
    void insert(StorageBO record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table storage
     *
     * @abatorgenerated Sun Jul 21 12:52:32 CST 2013
     */
    
    public abstract List selectAll(Object paramObject);

    public abstract List selectAlls(Object paramObject);
    public abstract Object selectAllOfCounts(Object paramObject);
    public Object  selectDaiyanshuliang();
    public List selectDaiyanPhao();
    public Object  selectBuhegeshuliang();
    public List  selectBuhege();
    
    int updateByPrimaryKey(StorageBO record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table storage
     *
     * @abatorgenerated Sun Jul 21 12:52:32 CST 2013
     */
    int updateByPrimaryKeySelective(StorageBO record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table storage
     *
     * @abatorgenerated Sun Jul 21 12:52:32 CST 2013
     */
    List selectByExample(StorageExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table storage
     *
     * @abatorgenerated Sun Jul 21 12:52:32 CST 2013
     */
    StorageBO selectByPrimaryKey(Integer id);
    
    StorageBO selectByCheckresult(String checkResult);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table storage
     *
     * @abatorgenerated Sun Jul 21 12:52:32 CST 2013
     */
    int deleteByExample(StorageExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table storage
     *
     * @abatorgenerated Sun Jul 21 12:52:32 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table storage
     *
     * @abatorgenerated Sun Jul 21 12:52:32 CST 2013
     */
    int countByExample(StorageExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table storage
     *
     * @abatorgenerated Sun Jul 21 12:52:32 CST 2013
     */
    int updateByExampleSelective(StorageBO record, StorageExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table storage
     *
     * @abatorgenerated Sun Jul 21 12:52:32 CST 2013
     */
    int updateByExample(StorageBO record, StorageExample example);

	Object selectAllOfCount(Object obj);

	Object queryData(StorageBO key);
}