package cn.krt.zbcg.commons.bo.system;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

public class ZhaobiaojinduExample {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table zhaobiaojindu
     *
     * @abatorgenerated Sat Aug 17 14:55:53 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table zhaobiaojindu
     *
     * @abatorgenerated Sat Aug 17 14:55:53 CST 2013
     */
    protected List oredCriteria;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zhaobiaojindu
     *
     * @abatorgenerated Sat Aug 17 14:55:53 CST 2013
     */
    public ZhaobiaojinduExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zhaobiaojindu
     *
     * @abatorgenerated Sat Aug 17 14:55:53 CST 2013
     */
    protected ZhaobiaojinduExample(ZhaobiaojinduExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zhaobiaojindu
     *
     * @abatorgenerated Sat Aug 17 14:55:53 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zhaobiaojindu
     *
     * @abatorgenerated Sat Aug 17 14:55:53 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zhaobiaojindu
     *
     * @abatorgenerated Sat Aug 17 14:55:53 CST 2013
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zhaobiaojindu
     *
     * @abatorgenerated Sat Aug 17 14:55:53 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zhaobiaojindu
     *
     * @abatorgenerated Sat Aug 17 14:55:53 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zhaobiaojindu
     *
     * @abatorgenerated Sat Aug 17 14:55:53 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table zhaobiaojindu
     *
     * @abatorgenerated Sat Aug 17 14:55:53 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table zhaobiaojindu
     *
     * @abatorgenerated Sat Aug 17 14:55:53 CST 2013
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List dateList = new ArrayList();
            Iterator iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(((Date)iter.next()).getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return this;
        }

        public Criteria andIdIn(List values) {
            addCriterion("id in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List values) {
            addCriterion("id not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return this;
        }

        public Criteria andDingdanhaoIsNull() {
            addCriterion("dingdanhao is null");
            return this;
        }

        public Criteria andDingdanhaoIsNotNull() {
            addCriterion("dingdanhao is not null");
            return this;
        }

        public Criteria andDingdanhaoEqualTo(String value) {
            addCriterion("dingdanhao =", value, "dingdanhao");
            return this;
        }

        public Criteria andDingdanhaoNotEqualTo(String value) {
            addCriterion("dingdanhao <>", value, "dingdanhao");
            return this;
        }

        public Criteria andDingdanhaoGreaterThan(String value) {
            addCriterion("dingdanhao >", value, "dingdanhao");
            return this;
        }

        public Criteria andDingdanhaoGreaterThanOrEqualTo(String value) {
            addCriterion("dingdanhao >=", value, "dingdanhao");
            return this;
        }

        public Criteria andDingdanhaoLessThan(String value) {
            addCriterion("dingdanhao <", value, "dingdanhao");
            return this;
        }

        public Criteria andDingdanhaoLessThanOrEqualTo(String value) {
            addCriterion("dingdanhao <=", value, "dingdanhao");
            return this;
        }

        public Criteria andDingdanhaoLike(String value) {
            addCriterion("dingdanhao like", value, "dingdanhao");
            return this;
        }

        public Criteria andDingdanhaoNotLike(String value) {
            addCriterion("dingdanhao not like", value, "dingdanhao");
            return this;
        }

        public Criteria andDingdanhaoIn(List values) {
            addCriterion("dingdanhao in", values, "dingdanhao");
            return this;
        }

        public Criteria andDingdanhaoNotIn(List values) {
            addCriterion("dingdanhao not in", values, "dingdanhao");
            return this;
        }

        public Criteria andDingdanhaoBetween(String value1, String value2) {
            addCriterion("dingdanhao between", value1, value2, "dingdanhao");
            return this;
        }

        public Criteria andDingdanhaoNotBetween(String value1, String value2) {
            addCriterion("dingdanhao not between", value1, value2, "dingdanhao");
            return this;
        }

        public Criteria andGonghuoshangIsNull() {
            addCriterion("gonghuoshang is null");
            return this;
        }

        public Criteria andGonghuoshangIsNotNull() {
            addCriterion("gonghuoshang is not null");
            return this;
        }

        public Criteria andGonghuoshangEqualTo(String value) {
            addCriterion("gonghuoshang =", value, "gonghuoshang");
            return this;
        }

        public Criteria andGonghuoshangNotEqualTo(String value) {
            addCriterion("gonghuoshang <>", value, "gonghuoshang");
            return this;
        }

        public Criteria andGonghuoshangGreaterThan(String value) {
            addCriterion("gonghuoshang >", value, "gonghuoshang");
            return this;
        }

        public Criteria andGonghuoshangGreaterThanOrEqualTo(String value) {
            addCriterion("gonghuoshang >=", value, "gonghuoshang");
            return this;
        }

        public Criteria andGonghuoshangLessThan(String value) {
            addCriterion("gonghuoshang <", value, "gonghuoshang");
            return this;
        }

        public Criteria andGonghuoshangLessThanOrEqualTo(String value) {
            addCriterion("gonghuoshang <=", value, "gonghuoshang");
            return this;
        }

        public Criteria andGonghuoshangLike(String value) {
            addCriterion("gonghuoshang like", value, "gonghuoshang");
            return this;
        }

        public Criteria andGonghuoshangNotLike(String value) {
            addCriterion("gonghuoshang not like", value, "gonghuoshang");
            return this;
        }

        public Criteria andGonghuoshangIn(List values) {
            addCriterion("gonghuoshang in", values, "gonghuoshang");
            return this;
        }

        public Criteria andGonghuoshangNotIn(List values) {
            addCriterion("gonghuoshang not in", values, "gonghuoshang");
            return this;
        }

        public Criteria andGonghuoshangBetween(String value1, String value2) {
            addCriterion("gonghuoshang between", value1, value2, "gonghuoshang");
            return this;
        }

        public Criteria andGonghuoshangNotBetween(String value1, String value2) {
            addCriterion("gonghuoshang not between", value1, value2, "gonghuoshang");
            return this;
        }

        public Criteria andXufangdanweiIsNull() {
            addCriterion("xufangdanwei is null");
            return this;
        }

        public Criteria andXufangdanweiIsNotNull() {
            addCriterion("xufangdanwei is not null");
            return this;
        }

        public Criteria andXufangdanweiEqualTo(String value) {
            addCriterion("xufangdanwei =", value, "xufangdanwei");
            return this;
        }

        public Criteria andXufangdanweiNotEqualTo(String value) {
            addCriterion("xufangdanwei <>", value, "xufangdanwei");
            return this;
        }

        public Criteria andXufangdanweiGreaterThan(String value) {
            addCriterion("xufangdanwei >", value, "xufangdanwei");
            return this;
        }

        public Criteria andXufangdanweiGreaterThanOrEqualTo(String value) {
            addCriterion("xufangdanwei >=", value, "xufangdanwei");
            return this;
        }

        public Criteria andXufangdanweiLessThan(String value) {
            addCriterion("xufangdanwei <", value, "xufangdanwei");
            return this;
        }

        public Criteria andXufangdanweiLessThanOrEqualTo(String value) {
            addCriterion("xufangdanwei <=", value, "xufangdanwei");
            return this;
        }

        public Criteria andXufangdanweiLike(String value) {
            addCriterion("xufangdanwei like", value, "xufangdanwei");
            return this;
        }

        public Criteria andXufangdanweiNotLike(String value) {
            addCriterion("xufangdanwei not like", value, "xufangdanwei");
            return this;
        }

        public Criteria andXufangdanweiIn(List values) {
            addCriterion("xufangdanwei in", values, "xufangdanwei");
            return this;
        }

        public Criteria andXufangdanweiNotIn(List values) {
            addCriterion("xufangdanwei not in", values, "xufangdanwei");
            return this;
        }

        public Criteria andXufangdanweiBetween(String value1, String value2) {
            addCriterion("xufangdanwei between", value1, value2, "xufangdanwei");
            return this;
        }

        public Criteria andXufangdanweiNotBetween(String value1, String value2) {
            addCriterion("xufangdanwei not between", value1, value2, "xufangdanwei");
            return this;
        }

        public Criteria andLianxirenIsNull() {
            addCriterion("lianxiren is null");
            return this;
        }

        public Criteria andLianxirenIsNotNull() {
            addCriterion("lianxiren is not null");
            return this;
        }

        public Criteria andLianxirenEqualTo(String value) {
            addCriterion("lianxiren =", value, "lianxiren");
            return this;
        }

        public Criteria andLianxirenNotEqualTo(String value) {
            addCriterion("lianxiren <>", value, "lianxiren");
            return this;
        }

        public Criteria andLianxirenGreaterThan(String value) {
            addCriterion("lianxiren >", value, "lianxiren");
            return this;
        }

        public Criteria andLianxirenGreaterThanOrEqualTo(String value) {
            addCriterion("lianxiren >=", value, "lianxiren");
            return this;
        }

        public Criteria andLianxirenLessThan(String value) {
            addCriterion("lianxiren <", value, "lianxiren");
            return this;
        }

        public Criteria andLianxirenLessThanOrEqualTo(String value) {
            addCriterion("lianxiren <=", value, "lianxiren");
            return this;
        }

        public Criteria andLianxirenLike(String value) {
            addCriterion("lianxiren like", value, "lianxiren");
            return this;
        }

        public Criteria andLianxirenNotLike(String value) {
            addCriterion("lianxiren not like", value, "lianxiren");
            return this;
        }

        public Criteria andLianxirenIn(List values) {
            addCriterion("lianxiren in", values, "lianxiren");
            return this;
        }

        public Criteria andLianxirenNotIn(List values) {
            addCriterion("lianxiren not in", values, "lianxiren");
            return this;
        }

        public Criteria andLianxirenBetween(String value1, String value2) {
            addCriterion("lianxiren between", value1, value2, "lianxiren");
            return this;
        }

        public Criteria andLianxirenNotBetween(String value1, String value2) {
            addCriterion("lianxiren not between", value1, value2, "lianxiren");
            return this;
        }

        public Criteria andKaibiaoriqiIsNull() {
            addCriterion("kaibiaoriqi is null");
            return this;
        }

        public Criteria andKaibiaoriqiIsNotNull() {
            addCriterion("kaibiaoriqi is not null");
            return this;
        }

        public Criteria andKaibiaoriqiEqualTo(Date value) {
            addCriterionForJDBCDate("kaibiaoriqi =", value, "kaibiaoriqi");
            return this;
        }

        public Criteria andKaibiaoriqiNotEqualTo(Date value) {
            addCriterionForJDBCDate("kaibiaoriqi <>", value, "kaibiaoriqi");
            return this;
        }

        public Criteria andKaibiaoriqiGreaterThan(Date value) {
            addCriterionForJDBCDate("kaibiaoriqi >", value, "kaibiaoriqi");
            return this;
        }

        public Criteria andKaibiaoriqiGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("kaibiaoriqi >=", value, "kaibiaoriqi");
            return this;
        }

        public Criteria andKaibiaoriqiLessThan(Date value) {
            addCriterionForJDBCDate("kaibiaoriqi <", value, "kaibiaoriqi");
            return this;
        }

        public Criteria andKaibiaoriqiLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("kaibiaoriqi <=", value, "kaibiaoriqi");
            return this;
        }

        public Criteria andKaibiaoriqiIn(List values) {
            addCriterionForJDBCDate("kaibiaoriqi in", values, "kaibiaoriqi");
            return this;
        }

        public Criteria andKaibiaoriqiNotIn(List values) {
            addCriterionForJDBCDate("kaibiaoriqi not in", values, "kaibiaoriqi");
            return this;
        }

        public Criteria andKaibiaoriqiBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("kaibiaoriqi between", value1, value2, "kaibiaoriqi");
            return this;
        }

        public Criteria andKaibiaoriqiNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("kaibiaoriqi not between", value1, value2, "kaibiaoriqi");
            return this;
        }

        public Criteria andDianhuaIsNull() {
            addCriterion("dianhua is null");
            return this;
        }

        public Criteria andDianhuaIsNotNull() {
            addCriterion("dianhua is not null");
            return this;
        }

        public Criteria andDianhuaEqualTo(String value) {
            addCriterion("dianhua =", value, "dianhua");
            return this;
        }

        public Criteria andDianhuaNotEqualTo(String value) {
            addCriterion("dianhua <>", value, "dianhua");
            return this;
        }

        public Criteria andDianhuaGreaterThan(String value) {
            addCriterion("dianhua >", value, "dianhua");
            return this;
        }

        public Criteria andDianhuaGreaterThanOrEqualTo(String value) {
            addCriterion("dianhua >=", value, "dianhua");
            return this;
        }

        public Criteria andDianhuaLessThan(String value) {
            addCriterion("dianhua <", value, "dianhua");
            return this;
        }

        public Criteria andDianhuaLessThanOrEqualTo(String value) {
            addCriterion("dianhua <=", value, "dianhua");
            return this;
        }

        public Criteria andDianhuaLike(String value) {
            addCriterion("dianhua like", value, "dianhua");
            return this;
        }

        public Criteria andDianhuaNotLike(String value) {
            addCriterion("dianhua not like", value, "dianhua");
            return this;
        }

        public Criteria andDianhuaIn(List values) {
            addCriterion("dianhua in", values, "dianhua");
            return this;
        }

        public Criteria andDianhuaNotIn(List values) {
            addCriterion("dianhua not in", values, "dianhua");
            return this;
        }

        public Criteria andDianhuaBetween(String value1, String value2) {
            addCriterion("dianhua between", value1, value2, "dianhua");
            return this;
        }

        public Criteria andDianhuaNotBetween(String value1, String value2) {
            addCriterion("dianhua not between", value1, value2, "dianhua");
            return this;
        }

        public Criteria andZcjdhrqIsNull() {
            addCriterion("zcjdhrq is null");
            return this;
        }

        public Criteria andZcjdhrqIsNotNull() {
            addCriterion("zcjdhrq is not null");
            return this;
        }

        public Criteria andZcjdhrqEqualTo(Date value) {
            addCriterionForJDBCDate("zcjdhrq =", value, "zcjdhrq");
            return this;
        }

        public Criteria andZcjdhrqNotEqualTo(Date value) {
            addCriterionForJDBCDate("zcjdhrq <>", value, "zcjdhrq");
            return this;
        }

        public Criteria andZcjdhrqGreaterThan(Date value) {
            addCriterionForJDBCDate("zcjdhrq >", value, "zcjdhrq");
            return this;
        }

        public Criteria andZcjdhrqGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("zcjdhrq >=", value, "zcjdhrq");
            return this;
        }

        public Criteria andZcjdhrqLessThan(Date value) {
            addCriterionForJDBCDate("zcjdhrq <", value, "zcjdhrq");
            return this;
        }

        public Criteria andZcjdhrqLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("zcjdhrq <=", value, "zcjdhrq");
            return this;
        }

        public Criteria andZcjdhrqIn(List values) {
            addCriterionForJDBCDate("zcjdhrq in", values, "zcjdhrq");
            return this;
        }

        public Criteria andZcjdhrqNotIn(List values) {
            addCriterionForJDBCDate("zcjdhrq not in", values, "zcjdhrq");
            return this;
        }

        public Criteria andZcjdhrqBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("zcjdhrq between", value1, value2, "zcjdhrq");
            return this;
        }

        public Criteria andZcjdhrqNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("zcjdhrq not between", value1, value2, "zcjdhrq");
            return this;
        }

        public Criteria andZbjjnrqIsNull() {
            addCriterion("zbjjnrq is null");
            return this;
        }

        public Criteria andZbjjnrqIsNotNull() {
            addCriterion("zbjjnrq is not null");
            return this;
        }

        public Criteria andZbjjnrqEqualTo(Date value) {
            addCriterionForJDBCDate("zbjjnrq =", value, "zbjjnrq");
            return this;
        }

        public Criteria andZbjjnrqNotEqualTo(Date value) {
            addCriterionForJDBCDate("zbjjnrq <>", value, "zbjjnrq");
            return this;
        }

        public Criteria andZbjjnrqGreaterThan(Date value) {
            addCriterionForJDBCDate("zbjjnrq >", value, "zbjjnrq");
            return this;
        }

        public Criteria andZbjjnrqGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("zbjjnrq >=", value, "zbjjnrq");
            return this;
        }

        public Criteria andZbjjnrqLessThan(Date value) {
            addCriterionForJDBCDate("zbjjnrq <", value, "zbjjnrq");
            return this;
        }

        public Criteria andZbjjnrqLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("zbjjnrq <=", value, "zbjjnrq");
            return this;
        }

        public Criteria andZbjjnrqIn(List values) {
            addCriterionForJDBCDate("zbjjnrq in", values, "zbjjnrq");
            return this;
        }

        public Criteria andZbjjnrqNotIn(List values) {
            addCriterionForJDBCDate("zbjjnrq not in", values, "zbjjnrq");
            return this;
        }

        public Criteria andZbjjnrqBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("zbjjnrq between", value1, value2, "zbjjnrq");
            return this;
        }

        public Criteria andZbjjnrqNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("zbjjnrq not between", value1, value2, "zbjjnrq");
            return this;
        }

        public Criteria andPinmingIsNull() {
            addCriterion("pinming is null");
            return this;
        }

        public Criteria andPinmingIsNotNull() {
            addCriterion("pinming is not null");
            return this;
        }

        public Criteria andPinmingEqualTo(String value) {
            addCriterion("pinming =", value, "pinming");
            return this;
        }

        public Criteria andPinmingNotEqualTo(String value) {
            addCriterion("pinming <>", value, "pinming");
            return this;
        }

        public Criteria andPinmingGreaterThan(String value) {
            addCriterion("pinming >", value, "pinming");
            return this;
        }

        public Criteria andPinmingGreaterThanOrEqualTo(String value) {
            addCriterion("pinming >=", value, "pinming");
            return this;
        }

        public Criteria andPinmingLessThan(String value) {
            addCriterion("pinming <", value, "pinming");
            return this;
        }

        public Criteria andPinmingLessThanOrEqualTo(String value) {
            addCriterion("pinming <=", value, "pinming");
            return this;
        }

        public Criteria andPinmingLike(String value) {
            addCriterion("pinming like", value, "pinming");
            return this;
        }

        public Criteria andPinmingNotLike(String value) {
            addCriterion("pinming not like", value, "pinming");
            return this;
        }

        public Criteria andPinmingIn(List values) {
            addCriterion("pinming in", values, "pinming");
            return this;
        }

        public Criteria andPinmingNotIn(List values) {
            addCriterion("pinming not in", values, "pinming");
            return this;
        }

        public Criteria andPinmingBetween(String value1, String value2) {
            addCriterion("pinming between", value1, value2, "pinming");
            return this;
        }

        public Criteria andPinmingNotBetween(String value1, String value2) {
            addCriterion("pinming not between", value1, value2, "pinming");
            return this;
        }

        public Criteria andShuliangIsNull() {
            addCriterion("shuliang is null");
            return this;
        }

        public Criteria andShuliangIsNotNull() {
            addCriterion("shuliang is not null");
            return this;
        }

        public Criteria andShuliangEqualTo(Float value) {
            addCriterion("shuliang =", value, "shuliang");
            return this;
        }

        public Criteria andShuliangNotEqualTo(Float value) {
            addCriterion("shuliang <>", value, "shuliang");
            return this;
        }

        public Criteria andShuliangGreaterThan(Float value) {
            addCriterion("shuliang >", value, "shuliang");
            return this;
        }

        public Criteria andShuliangGreaterThanOrEqualTo(Float value) {
            addCriterion("shuliang >=", value, "shuliang");
            return this;
        }

        public Criteria andShuliangLessThan(Float value) {
            addCriterion("shuliang <", value, "shuliang");
            return this;
        }

        public Criteria andShuliangLessThanOrEqualTo(Float value) {
            addCriterion("shuliang <=", value, "shuliang");
            return this;
        }

        public Criteria andShuliangIn(List values) {
            addCriterion("shuliang in", values, "shuliang");
            return this;
        }

        public Criteria andShuliangNotIn(List values) {
            addCriterion("shuliang not in", values, "shuliang");
            return this;
        }

        public Criteria andShuliangBetween(Float value1, Float value2) {
            addCriterion("shuliang between", value1, value2, "shuliang");
            return this;
        }

        public Criteria andShuliangNotBetween(Float value1, Float value2) {
            addCriterion("shuliang not between", value1, value2, "shuliang");
            return this;
        }

        public Criteria andChandiIsNull() {
            addCriterion("chandi is null");
            return this;
        }

        public Criteria andChandiIsNotNull() {
            addCriterion("chandi is not null");
            return this;
        }

        public Criteria andChandiEqualTo(String value) {
            addCriterion("chandi =", value, "chandi");
            return this;
        }

        public Criteria andChandiNotEqualTo(String value) {
            addCriterion("chandi <>", value, "chandi");
            return this;
        }

        public Criteria andChandiGreaterThan(String value) {
            addCriterion("chandi >", value, "chandi");
            return this;
        }

        public Criteria andChandiGreaterThanOrEqualTo(String value) {
            addCriterion("chandi >=", value, "chandi");
            return this;
        }

        public Criteria andChandiLessThan(String value) {
            addCriterion("chandi <", value, "chandi");
            return this;
        }

        public Criteria andChandiLessThanOrEqualTo(String value) {
            addCriterion("chandi <=", value, "chandi");
            return this;
        }

        public Criteria andChandiLike(String value) {
            addCriterion("chandi like", value, "chandi");
            return this;
        }

        public Criteria andChandiNotLike(String value) {
            addCriterion("chandi not like", value, "chandi");
            return this;
        }

        public Criteria andChandiIn(List values) {
            addCriterion("chandi in", values, "chandi");
            return this;
        }

        public Criteria andChandiNotIn(List values) {
            addCriterion("chandi not in", values, "chandi");
            return this;
        }

        public Criteria andChandiBetween(String value1, String value2) {
            addCriterion("chandi between", value1, value2, "chandi");
            return this;
        }

        public Criteria andChandiNotBetween(String value1, String value2) {
            addCriterion("chandi not between", value1, value2, "chandi");
            return this;
        }

        public Criteria andDanjiaIsNull() {
            addCriterion("danjia is null");
            return this;
        }

        public Criteria andDanjiaIsNotNull() {
            addCriterion("danjia is not null");
            return this;
        }

        public Criteria andDanjiaEqualTo(Float value) {
            addCriterion("danjia =", value, "danjia");
            return this;
        }

        public Criteria andDanjiaNotEqualTo(Float value) {
            addCriterion("danjia <>", value, "danjia");
            return this;
        }

        public Criteria andDanjiaGreaterThan(Float value) {
            addCriterion("danjia >", value, "danjia");
            return this;
        }

        public Criteria andDanjiaGreaterThanOrEqualTo(Float value) {
            addCriterion("danjia >=", value, "danjia");
            return this;
        }

        public Criteria andDanjiaLessThan(Float value) {
            addCriterion("danjia <", value, "danjia");
            return this;
        }

        public Criteria andDanjiaLessThanOrEqualTo(Float value) {
            addCriterion("danjia <=", value, "danjia");
            return this;
        }

        public Criteria andDanjiaIn(List values) {
            addCriterion("danjia in", values, "danjia");
            return this;
        }

        public Criteria andDanjiaNotIn(List values) {
            addCriterion("danjia not in", values, "danjia");
            return this;
        }

        public Criteria andDanjiaBetween(Float value1, Float value2) {
            addCriterion("danjia between", value1, value2, "danjia");
            return this;
        }

        public Criteria andDanjiaNotBetween(Float value1, Float value2) {
            addCriterion("danjia not between", value1, value2, "danjia");
            return this;
        }

        public Criteria andJineIsNull() {
            addCriterion("jine is null");
            return this;
        }

        public Criteria andJineIsNotNull() {
            addCriterion("jine is not null");
            return this;
        }

        public Criteria andJineEqualTo(Float value) {
            addCriterion("jine =", value, "jine");
            return this;
        }

        public Criteria andJineNotEqualTo(Float value) {
            addCriterion("jine <>", value, "jine");
            return this;
        }

        public Criteria andJineGreaterThan(Float value) {
            addCriterion("jine >", value, "jine");
            return this;
        }

        public Criteria andJineGreaterThanOrEqualTo(Float value) {
            addCriterion("jine >=", value, "jine");
            return this;
        }

        public Criteria andJineLessThan(Float value) {
            addCriterion("jine <", value, "jine");
            return this;
        }

        public Criteria andJineLessThanOrEqualTo(Float value) {
            addCriterion("jine <=", value, "jine");
            return this;
        }

        public Criteria andJineIn(List values) {
            addCriterion("jine in", values, "jine");
            return this;
        }

        public Criteria andJineNotIn(List values) {
            addCriterion("jine not in", values, "jine");
            return this;
        }

        public Criteria andJineBetween(Float value1, Float value2) {
            addCriterion("jine between", value1, value2, "jine");
            return this;
        }

        public Criteria andJineNotBetween(Float value1, Float value2) {
            addCriterion("jine not between", value1, value2, "jine");
            return this;
        }

        public Criteria andZhibaojinIsNull() {
            addCriterion("zhibaojin is null");
            return this;
        }

        public Criteria andZhibaojinIsNotNull() {
            addCriterion("zhibaojin is not null");
            return this;
        }

        public Criteria andZhibaojinEqualTo(Float value) {
            addCriterion("zhibaojin =", value, "zhibaojin");
            return this;
        }

        public Criteria andZhibaojinNotEqualTo(Float value) {
            addCriterion("zhibaojin <>", value, "zhibaojin");
            return this;
        }

        public Criteria andZhibaojinGreaterThan(Float value) {
            addCriterion("zhibaojin >", value, "zhibaojin");
            return this;
        }

        public Criteria andZhibaojinGreaterThanOrEqualTo(Float value) {
            addCriterion("zhibaojin >=", value, "zhibaojin");
            return this;
        }

        public Criteria andZhibaojinLessThan(Float value) {
            addCriterion("zhibaojin <", value, "zhibaojin");
            return this;
        }

        public Criteria andZhibaojinLessThanOrEqualTo(Float value) {
            addCriterion("zhibaojin <=", value, "zhibaojin");
            return this;
        }

        public Criteria andZhibaojinIn(List values) {
            addCriterion("zhibaojin in", values, "zhibaojin");
            return this;
        }

        public Criteria andZhibaojinNotIn(List values) {
            addCriterion("zhibaojin not in", values, "zhibaojin");
            return this;
        }

        public Criteria andZhibaojinBetween(Float value1, Float value2) {
            addCriterion("zhibaojin between", value1, value2, "zhibaojin");
            return this;
        }

        public Criteria andZhibaojinNotBetween(Float value1, Float value2) {
            addCriterion("zhibaojin not between", value1, value2, "zhibaojin");
            return this;
        }

        public Criteria andZhuangxiefeiIsNull() {
            addCriterion("zhuangxiefei is null");
            return this;
        }

        public Criteria andZhuangxiefeiIsNotNull() {
            addCriterion("zhuangxiefei is not null");
            return this;
        }

        public Criteria andZhuangxiefeiEqualTo(Float value) {
            addCriterion("zhuangxiefei =", value, "zhuangxiefei");
            return this;
        }

        public Criteria andZhuangxiefeiNotEqualTo(Float value) {
            addCriterion("zhuangxiefei <>", value, "zhuangxiefei");
            return this;
        }

        public Criteria andZhuangxiefeiGreaterThan(Float value) {
            addCriterion("zhuangxiefei >", value, "zhuangxiefei");
            return this;
        }

        public Criteria andZhuangxiefeiGreaterThanOrEqualTo(Float value) {
            addCriterion("zhuangxiefei >=", value, "zhuangxiefei");
            return this;
        }

        public Criteria andZhuangxiefeiLessThan(Float value) {
            addCriterion("zhuangxiefei <", value, "zhuangxiefei");
            return this;
        }

        public Criteria andZhuangxiefeiLessThanOrEqualTo(Float value) {
            addCriterion("zhuangxiefei <=", value, "zhuangxiefei");
            return this;
        }

        public Criteria andZhuangxiefeiIn(List values) {
            addCriterion("zhuangxiefei in", values, "zhuangxiefei");
            return this;
        }

        public Criteria andZhuangxiefeiNotIn(List values) {
            addCriterion("zhuangxiefei not in", values, "zhuangxiefei");
            return this;
        }

        public Criteria andZhuangxiefeiBetween(Float value1, Float value2) {
            addCriterion("zhuangxiefei between", value1, value2, "zhuangxiefei");
            return this;
        }

        public Criteria andZhuangxiefeiNotBetween(Float value1, Float value2) {
            addCriterion("zhuangxiefei not between", value1, value2, "zhuangxiefei");
            return this;
        }

        public Criteria andQrjhrqIsNull() {
            addCriterion("qrjhrq is null");
            return this;
        }

        public Criteria andQrjhrqIsNotNull() {
            addCriterion("qrjhrq is not null");
            return this;
        }

        public Criteria andQrjhrqEqualTo(Date value) {
            addCriterionForJDBCDate("qrjhrq =", value, "qrjhrq");
            return this;
        }

        public Criteria andQrjhrqNotEqualTo(Date value) {
            addCriterionForJDBCDate("qrjhrq <>", value, "qrjhrq");
            return this;
        }

        public Criteria andQrjhrqGreaterThan(Date value) {
            addCriterionForJDBCDate("qrjhrq >", value, "qrjhrq");
            return this;
        }

        public Criteria andQrjhrqGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("qrjhrq >=", value, "qrjhrq");
            return this;
        }

        public Criteria andQrjhrqLessThan(Date value) {
            addCriterionForJDBCDate("qrjhrq <", value, "qrjhrq");
            return this;
        }

        public Criteria andQrjhrqLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("qrjhrq <=", value, "qrjhrq");
            return this;
        }

        public Criteria andQrjhrqIn(List values) {
            addCriterionForJDBCDate("qrjhrq in", values, "qrjhrq");
            return this;
        }

        public Criteria andQrjhrqNotIn(List values) {
            addCriterionForJDBCDate("qrjhrq not in", values, "qrjhrq");
            return this;
        }

        public Criteria andQrjhrqBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("qrjhrq between", value1, value2, "qrjhrq");
            return this;
        }

        public Criteria andQrjhrqNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("qrjhrq not between", value1, value2, "qrjhrq");
            return this;
        }

        public Criteria andPinzhongshuxingIsNull() {
            addCriterion("pinzhongshuxing is null");
            return this;
        }

        public Criteria andPinzhongshuxingIsNotNull() {
            addCriterion("pinzhongshuxing is not null");
            return this;
        }

        public Criteria andPinzhongshuxingEqualTo(String value) {
            addCriterion("pinzhongshuxing =", value, "pinzhongshuxing");
            return this;
        }

        public Criteria andPinzhongshuxingNotEqualTo(String value) {
            addCriterion("pinzhongshuxing <>", value, "pinzhongshuxing");
            return this;
        }

        public Criteria andPinzhongshuxingGreaterThan(String value) {
            addCriterion("pinzhongshuxing >", value, "pinzhongshuxing");
            return this;
        }

        public Criteria andPinzhongshuxingGreaterThanOrEqualTo(String value) {
            addCriterion("pinzhongshuxing >=", value, "pinzhongshuxing");
            return this;
        }

        public Criteria andPinzhongshuxingLessThan(String value) {
            addCriterion("pinzhongshuxing <", value, "pinzhongshuxing");
            return this;
        }

        public Criteria andPinzhongshuxingLessThanOrEqualTo(String value) {
            addCriterion("pinzhongshuxing <=", value, "pinzhongshuxing");
            return this;
        }

        public Criteria andPinzhongshuxingLike(String value) {
            addCriterion("pinzhongshuxing like", value, "pinzhongshuxing");
            return this;
        }

        public Criteria andPinzhongshuxingNotLike(String value) {
            addCriterion("pinzhongshuxing not like", value, "pinzhongshuxing");
            return this;
        }

        public Criteria andPinzhongshuxingIn(List values) {
            addCriterion("pinzhongshuxing in", values, "pinzhongshuxing");
            return this;
        }

        public Criteria andPinzhongshuxingNotIn(List values) {
            addCriterion("pinzhongshuxing not in", values, "pinzhongshuxing");
            return this;
        }

        public Criteria andPinzhongshuxingBetween(String value1, String value2) {
            addCriterion("pinzhongshuxing between", value1, value2, "pinzhongshuxing");
            return this;
        }

        public Criteria andPinzhongshuxingNotBetween(String value1, String value2) {
            addCriterion("pinzhongshuxing not between", value1, value2, "pinzhongshuxing");
            return this;
        }

        public Criteria andBeizhuIsNull() {
            addCriterion("beizhu is null");
            return this;
        }

        public Criteria andBeizhuIsNotNull() {
            addCriterion("beizhu is not null");
            return this;
        }

        public Criteria andBeizhuEqualTo(String value) {
            addCriterion("beizhu =", value, "beizhu");
            return this;
        }

        public Criteria andBeizhuNotEqualTo(String value) {
            addCriterion("beizhu <>", value, "beizhu");
            return this;
        }

        public Criteria andBeizhuGreaterThan(String value) {
            addCriterion("beizhu >", value, "beizhu");
            return this;
        }

        public Criteria andBeizhuGreaterThanOrEqualTo(String value) {
            addCriterion("beizhu >=", value, "beizhu");
            return this;
        }

        public Criteria andBeizhuLessThan(String value) {
            addCriterion("beizhu <", value, "beizhu");
            return this;
        }

        public Criteria andBeizhuLessThanOrEqualTo(String value) {
            addCriterion("beizhu <=", value, "beizhu");
            return this;
        }

        public Criteria andBeizhuLike(String value) {
            addCriterion("beizhu like", value, "beizhu");
            return this;
        }

        public Criteria andBeizhuNotLike(String value) {
            addCriterion("beizhu not like", value, "beizhu");
            return this;
        }

        public Criteria andBeizhuIn(List values) {
            addCriterion("beizhu in", values, "beizhu");
            return this;
        }

        public Criteria andBeizhuNotIn(List values) {
            addCriterion("beizhu not in", values, "beizhu");
            return this;
        }

        public Criteria andBeizhuBetween(String value1, String value2) {
            addCriterion("beizhu between", value1, value2, "beizhu");
            return this;
        }

        public Criteria andBeizhuNotBetween(String value1, String value2) {
            addCriterion("beizhu not between", value1, value2, "beizhu");
            return this;
        }

        public Criteria andZhibaojinjnrqIsNull() {
            addCriterion("zhibaojinjnrq is null");
            return this;
        }

        public Criteria andZhibaojinjnrqIsNotNull() {
            addCriterion("zhibaojinjnrq is not null");
            return this;
        }

        public Criteria andZhibaojinjnrqEqualTo(Date value) {
            addCriterionForJDBCDate("zhibaojinjnrq =", value, "zhibaojinjnrq");
            return this;
        }

        public Criteria andZhibaojinjnrqNotEqualTo(Date value) {
            addCriterionForJDBCDate("zhibaojinjnrq <>", value, "zhibaojinjnrq");
            return this;
        }

        public Criteria andZhibaojinjnrqGreaterThan(Date value) {
            addCriterionForJDBCDate("zhibaojinjnrq >", value, "zhibaojinjnrq");
            return this;
        }

        public Criteria andZhibaojinjnrqGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("zhibaojinjnrq >=", value, "zhibaojinjnrq");
            return this;
        }

        public Criteria andZhibaojinjnrqLessThan(Date value) {
            addCriterionForJDBCDate("zhibaojinjnrq <", value, "zhibaojinjnrq");
            return this;
        }

        public Criteria andZhibaojinjnrqLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("zhibaojinjnrq <=", value, "zhibaojinjnrq");
            return this;
        }

        public Criteria andZhibaojinjnrqIn(List values) {
            addCriterionForJDBCDate("zhibaojinjnrq in", values, "zhibaojinjnrq");
            return this;
        }

        public Criteria andZhibaojinjnrqNotIn(List values) {
            addCriterionForJDBCDate("zhibaojinjnrq not in", values, "zhibaojinjnrq");
            return this;
        }

        public Criteria andZhibaojinjnrqBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("zhibaojinjnrq between", value1, value2, "zhibaojinjnrq");
            return this;
        }

        public Criteria andZhibaojinjnrqNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("zhibaojinjnrq not between", value1, value2, "zhibaojinjnrq");
            return this;
        }

        public Criteria andYingtuizhibaojinIsNull() {
            addCriterion("yingtuizhibaojin is null");
            return this;
        }

        public Criteria andYingtuizhibaojinIsNotNull() {
            addCriterion("yingtuizhibaojin is not null");
            return this;
        }

        public Criteria andYingtuizhibaojinEqualTo(Float value) {
            addCriterion("yingtuizhibaojin =", value, "yingtuizhibaojin");
            return this;
        }

        public Criteria andYingtuizhibaojinNotEqualTo(Float value) {
            addCriterion("yingtuizhibaojin <>", value, "yingtuizhibaojin");
            return this;
        }

        public Criteria andYingtuizhibaojinGreaterThan(Float value) {
            addCriterion("yingtuizhibaojin >", value, "yingtuizhibaojin");
            return this;
        }

        public Criteria andYingtuizhibaojinGreaterThanOrEqualTo(Float value) {
            addCriterion("yingtuizhibaojin >=", value, "yingtuizhibaojin");
            return this;
        }

        public Criteria andYingtuizhibaojinLessThan(Float value) {
            addCriterion("yingtuizhibaojin <", value, "yingtuizhibaojin");
            return this;
        }

        public Criteria andYingtuizhibaojinLessThanOrEqualTo(Float value) {
            addCriterion("yingtuizhibaojin <=", value, "yingtuizhibaojin");
            return this;
        }

        public Criteria andYingtuizhibaojinIn(List values) {
            addCriterion("yingtuizhibaojin in", values, "yingtuizhibaojin");
            return this;
        }

        public Criteria andYingtuizhibaojinNotIn(List values) {
            addCriterion("yingtuizhibaojin not in", values, "yingtuizhibaojin");
            return this;
        }

        public Criteria andYingtuizhibaojinBetween(Float value1, Float value2) {
            addCriterion("yingtuizhibaojin between", value1, value2, "yingtuizhibaojin");
            return this;
        }

        public Criteria andYingtuizhibaojinNotBetween(Float value1, Float value2) {
            addCriterion("yingtuizhibaojin not between", value1, value2, "yingtuizhibaojin");
            return this;
        }
    }
}