package cn.krt.zbcg.system.dao.impl;

import cn.krt.zbcg.commons.bo.system.FapiaoinfoBO;
import cn.krt.zbcg.commons.bo.system.FukuandetailBO;
import cn.krt.zbcg.commons.bo.system.FukuandetailExample;
import cn.krt.zbcg.system.dao.IFukuandetailDAO;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import org.ssi.dao.impl.BaseDaoImpl;

public class FukuandetailDAOImpl  extends BaseDaoImpl implements IFukuandetailDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table fukuandetail
     *
     * @abatorgenerated Wed Aug 14 22:01:38 CST 2013
     */
    public FukuandetailDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table fukuandetail
     *
     * @abatorgenerated Wed Aug 14 22:01:38 CST 2013
     */
    public void insert(FukuandetailBO record) {
        getSqlMapClientTemplate().insert("fukuandetail.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table fukuandetail
     *
     * @abatorgenerated Wed Aug 14 22:01:38 CST 2013
     */
    public int updateByPrimaryKey(FukuandetailBO record) {
        int rows = getSqlMapClientTemplate().update("fukuandetail.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table fukuandetail
     *
     * @abatorgenerated Wed Aug 14 22:01:38 CST 2013
     */
    public int updateByPrimaryKeySelective(FukuandetailBO record) {
        int rows = getSqlMapClientTemplate().update("fukuandetail.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table fukuandetail
     *
     * @abatorgenerated Wed Aug 14 22:01:38 CST 2013
     */
    public List selectByExample(FukuandetailExample example) {
        List list = getSqlMapClientTemplate().queryForList("fukuandetail.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table fukuandetail
     *
     * @abatorgenerated Wed Aug 14 22:01:38 CST 2013
     */
    public FukuandetailBO selectByPrimaryKey(Integer id) {
        FukuandetailBO key = new FukuandetailBO();
        key.setId(id);
        FukuandetailBO record = (FukuandetailBO) getSqlMapClientTemplate().queryForObject("fukuandetail.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table fukuandetail
     *
     * @abatorgenerated Wed Aug 14 22:01:38 CST 2013
     */
    public int deleteByExample(FukuandetailExample example) {
        int rows = getSqlMapClientTemplate().delete("fukuandetail.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table fukuandetail
     *
     * @abatorgenerated Wed Aug 14 22:01:38 CST 2013
     */
    public int deleteByPrimaryKey(Integer id) {
        FukuandetailBO key = new FukuandetailBO();
        key.setId(id);
        int rows = 0;
        try{
         rows = getSqlMapClientTemplate().delete("fukuandetail.deleteByPrimaryKey", key);
        }catch(Exception e){
        	e.printStackTrace();
        }
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table fukuandetail
     *
     * @abatorgenerated Wed Aug 14 22:01:38 CST 2013
     */
    public int countByExample(FukuandetailExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("fukuandetail.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table fukuandetail
     *
     * @abatorgenerated Wed Aug 14 22:01:38 CST 2013
     */
    public int updateByExampleSelective(FukuandetailBO record, FukuandetailExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("fukuandetail.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table fukuandetail
     *
     * @abatorgenerated Wed Aug 14 22:01:38 CST 2013
     */
    public int updateByExample(FukuandetailBO record, FukuandetailExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("fukuandetail.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table fukuandetail
     *
     * @abatorgenerated Wed Aug 14 22:01:38 CST 2013
     */
    private static class UpdateByExampleParms extends FukuandetailExample {
        private Object record;

        public UpdateByExampleParms(Object record, FukuandetailExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
    
    @Override
	public List selectAll(Object paramObject) {
		List list = queryList("fukuandetail.selectAll", paramObject);
		return list;
	}

	@Override
	public Object selectAllOfCount(Object obj) {
		List list = queryList("fukuandetail.selectAll", obj);
		return list;
	}

	@Override
	public List selectAlls(Object paramObject) {
		List list = queryList("fukuandetail.selectAll", paramObject);
		return list;
	}

	@Override
	public Object selectAllOfCounts(Object paramObject) {
		List list = queryList("fukuandetail.selectAll", paramObject);
		return list;
	}
	
	  public Object queryData(Object obj)
      {
       Object record = queryData("fukuandetail.selectByPrimaryKey", obj);
        return record;
     }



	@Override
	public int update(FukuandetailBO record) throws Exception {
		  int rows = update("fukuandetail.updateByPrimaryKey", record);
		    return rows;
	}

	@Override
	public FukuandetailBO queryData(FukuandetailBO key) {
		FukuandetailBO record = (FukuandetailBO) queryData("fukuandetail.selectByPrimaryKey", key);
	        return record;
	}
    
}