package cn.krt.zbcg.system.dao.impl;

import cn.krt.zbcg.commons.bo.system.ShqdheadBO;
import cn.krt.zbcg.commons.bo.system.ShqdheadExample;
import cn.krt.zbcg.system.dao.ShqdheadDAO;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import org.ssi.dao.impl.BaseDaoImpl;

public class ShqdheadDAOImpl  extends BaseDaoImpl  implements ShqdheadDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shqdhead
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    public ShqdheadDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shqdhead
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    public void insert(ShqdheadBO record) {
        getSqlMapClientTemplate().insert("shqdhead.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shqdhead
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    public int updateByPrimaryKey(ShqdheadBO record) {
        int rows = getSqlMapClientTemplate().update("shqdhead.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shqdhead
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    public int updateByPrimaryKeySelective(ShqdheadBO record) {
        int rows = getSqlMapClientTemplate().update("shqdhead.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shqdhead
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    public List selectByExample(ShqdheadExample example) {
        List list = getSqlMapClientTemplate().queryForList("shqdhead.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shqdhead
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    public ShqdheadBO selectByPrimaryKey(Integer id) {
        ShqdheadBO key = new ShqdheadBO();
        key.setId(id);
        ShqdheadBO record = (ShqdheadBO) getSqlMapClientTemplate().queryForObject("shqdhead.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shqdhead
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    public int deleteByExample(ShqdheadExample example) {
        int rows = getSqlMapClientTemplate().delete("shqdhead.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shqdhead
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    public int deleteByPrimaryKey(Integer id) {
        ShqdheadBO key = new ShqdheadBO();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("shqdhead.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shqdhead
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    public int countByExample(ShqdheadExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("shqdhead.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shqdhead
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    public int updateByExampleSelective(ShqdheadBO record, ShqdheadExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("shqdhead.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table shqdhead
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    public int updateByExample(ShqdheadBO record, ShqdheadExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("shqdhead.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table shqdhead
     *
     * @abatorgenerated Sat Sep 14 14:52:37 CST 2013
     */
    private static class UpdateByExampleParms extends ShqdheadExample {
        private Object record;

        public UpdateByExampleParms(Object record, ShqdheadExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
    
    public List selectAll(Object obj) {
		List list = queryList("shqdhead.selectAll", obj);
		return list;
	}

	public List selectAlls(Object obj) {
		List list = queryList("shqdhead.selectAlls", obj);
		return list;
	}

	public Object selectAllOfCount(Object obj) {
		Object o = queryData("shqdhead.selectAllOfCount", obj);
		return o;
	}
	
	public Object selectAllOfCounts(Object obj) {
		Object o = queryData("shqdhead.selectAllOfCounts", obj);
		return o;
	}
}